export type LangCode =
  | "en" | "hi" | "bn" | "ta" | "te" | "mr"
  | "gu" | "kn" | "ml" | "pa" | "or" | "as";

export interface Language {
  code: LangCode;
  name: string;
  native: string;
  bcp47: string;
  greeting: string;
}

export const LANGUAGES: Language[] = [
  { code: "hi", name: "Hindi",      native: "हिन्दी",     bcp47: "hi-IN", greeting: "नमस्ते, मैं न्यायसखी हूँ" },
  { code: "en", name: "English",    native: "English",    bcp47: "en-IN", greeting: "Hello, I am NyayaSakhi" },
  { code: "bn", name: "Bengali",    native: "বাংলা",      bcp47: "bn-IN", greeting: "নমস্কার, আমি ন্যায়সখী" },
  { code: "ta", name: "Tamil",      native: "தமிழ்",      bcp47: "ta-IN", greeting: "வணக்கம், நான் நியாயசகி" },
  { code: "te", name: "Telugu",     native: "తెలుగు",     bcp47: "te-IN", greeting: "నమస్తే, నేను న్యాయసఖి" },
  { code: "mr", name: "Marathi",    native: "मराठी",      bcp47: "mr-IN", greeting: "नमस्कार, मी न्यायसखी आहे" },
  { code: "gu", name: "Gujarati",   native: "ગુજરાતી",   bcp47: "gu-IN", greeting: "નમસ્તે, હું ન્યાયસખી છું" },
  { code: "kn", name: "Kannada",    native: "ಕನ್ನಡ",      bcp47: "kn-IN", greeting: "ನಮಸ್ಕಾರ, ನಾನು ನ್ಯಾಯಸಖಿ" },
  { code: "ml", name: "Malayalam",  native: "മലയാളം",    bcp47: "ml-IN", greeting: "നമസ്കാരം, ഞാൻ ന്യായസഖി" },
  { code: "pa", name: "Punjabi",    native: "ਪੰਜਾਬੀ",     bcp47: "pa-IN", greeting: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ, ਮੈਂ ਨਿਆਂਸਖੀ ਹਾਂ" },
  { code: "or", name: "Odia",       native: "ଓଡ଼ିଆ",      bcp47: "or-IN", greeting: "ନମସ୍କାର, ମୁଁ ନ୍ୟାୟସଖୀ" },
  { code: "as", name: "Assamese",   native: "অসমীয়া",    bcp47: "as-IN", greeting: "নমস্কাৰ, মই ন্যায়সখী" },
];

export const getLang = (code: LangCode) =>
  LANGUAGES.find(l => l.code === code) ?? LANGUAGES[0];

type StringKey =
  | "tagline" | "subtitle" | "startTalking" | "chooseLanguage" | "findHelp"
  | "knowRights" | "saveCase" | "heroCtaPrimary" | "heroCtaSecondary" | "heroCtaGuidance"
  | "chatPlaceholder" | "send" | "tapToSpeak" | "listening" | "speaking"
  | "directoryTitle" | "directorySub" | "selectState" | "callNow" | "lawyers" | "ngos" | "helplines"
  | "all" | "search" | "noResults"
  | "guidanceTitle" | "guidanceSub" | "disclaimer" | "back"
  | "feature1Title" | "feature1Desc" | "feature2Title" | "feature2Desc" | "feature3Title" | "feature3Desc"
  | "loginOptional" | "anonymous"
  | "forRuralWomen" | "talkingIn" | "womenHelpline" | "ctaTitle" | "ctaDesc"
  | "footerNote"
  | "docsTitle" | "docsSub" | "docsIdentity" | "docsIdentityDesc"
  | "docsProperty" | "docsPropertyDesc" | "docsRelationship" | "docsRelationshipDesc"
  | "docsDeath" | "docsDeathDesc" | "docsLegal" | "docsLegalDesc"
  | "docsTip" | "docsTipText"
  | "wizardIntro" | "wizardPickCase" | "wizardStep" | "wizardOf" | "wizardNext" | "wizardPrev"
  | "wizardRestart" | "wizardYourChecklist" | "wizardWhyThis" | "wizardNextSteps"
  | "wizardAskChat" | "wizardFindHelp"
  | "caseFatherTitle" | "caseFatherDesc"
  | "caseHusbandTitle" | "caseHusbandDesc"
  | "caseDeniedTitle" | "caseDeniedDesc"
  | "caseAgriTitle" | "caseAgriDesc"
  | "qWillTitle" | "qWillYes" | "qWillNo" | "qWillUnknown"
  | "qReligionTitle" | "qHindu" | "qMuslim" | "qChristian" | "qOther"
  | "qLandTitle" | "qLandYes" | "qLandNo"
  | "stepWill" | "stepReligion" | "stepLand"
  | "nextFatherDLSA" | "nextFatherMutation" | "nextFatherFIR"
  | "nextHusbandSuccession" | "nextHusbandShare"
  | "nextDeniedNotice" | "nextDeniedSection6"
  | "nextAgriPatta" | "nextAgriRevenue"
  | "heroCtaUpload"
  | "docUpTitle" | "docUpSub" | "docUpChoose" | "docUpMax"
  | "docUpReading" | "docUpThinking" | "docUpExplanation"
  | "docUpListen" | "docUpAnother"
  | "docUpTooBig" | "docUpUnsupported" | "docUpNoText" | "docUpExtractFail";


export const UI: Record<LangCode, Partial<Record<StringKey, string>>> = {
  en: {
    tagline: "Your voice. Your rights. Your inheritance.",
    subtitle: "A gentle, voice-first guide for rural women in India to understand inheritance rights and find nearby legal help — in your own language.",
    heroCtaPrimary: "Start talking",
    heroCtaSecondary: "Find legal help",
    heroCtaGuidance: "Simple legal guidance",
    heroCtaUpload: "Understand a document",
    docUpTitle: "Understand a document",
    docUpSub: "Upload a PDF or photo of any letter, notice or paper. We'll explain it in simple words.",
    docUpChoose: "Choose a file",
    docUpMax: "max 10 MB",
    docUpReading: "Reading the document…",
    docUpThinking: "NyayaSakhi is thinking…",
    docUpExplanation: "Simple explanation",
    docUpListen: "Listen again",
    docUpAnother: "Upload another",
    docUpTooBig: "File is too large (max 10 MB).",
    docUpUnsupported: "Please upload a PDF or image.",
    docUpNoText: "Could not read any text from this file. Try a clearer photo.",
    docUpExtractFail: "Could not read this document. Please try again.",
    chooseLanguage: "Choose your language",
    chatPlaceholder: "Type or tap the mic to speak…",
    send: "Send", tapToSpeak: "Tap to speak", listening: "Listening…", speaking: "Speaking…",
    directoryTitle: "Nearby legal help",
    directorySub: "Free legal aid, NGOs and women's helplines across India.",
    selectState: "Select your state", callNow: "Call now",
    lawyers: "Legal Aid", ngos: "NGOs", helplines: "Helplines",
    all: "All", search: "Search…", noResults: "No contacts match your search.",
    guidanceTitle: "Voice chatbot",
    guidanceSub: "Ask anything about your inheritance rights.",
    disclaimer: "This is general guidance, not a substitute for a lawyer.",
    back: "Back",
    feature1Title: "Talk in your language",
    feature1Desc: "12 Indian languages with voice in and voice out.",
    feature2Title: "Simple legal guidance",
    feature2Desc: "Plain answers about your share, daughters' rights, and the law.",
    feature3Title: "Real human help nearby",
    feature3Desc: "Free legal aid, NGOs, and women's helplines in your state.",
    anonymous: "Continue without login",
    loginOptional: "Save my case (optional)",
    forRuralWomen: "For rural women across India · 12 languages",
    talkingIn: "Talking in",
    womenHelpline: "Women Helpline · 24×7",
    ctaTitle: "Ready to know your rights?",
    ctaDesc: "Speak in your language. No reading or typing needed. NyayaSakhi listens, answers, and reads back.",
    footerNote: "Made with care for the women of India.",
    docsTitle: "Documents you may need",
    docsSub: "A simple checklist of papers that help in inheritance and property cases. Keep copies safely.",
    docsIdentity: "Identity proof",
    docsIdentityDesc: "Aadhaar card, Voter ID, PAN card, ration card, or passport — for you and the deceased.",
    docsProperty: "Property documents",
    docsPropertyDesc: "Sale deed, gift deed, patta, 7/12 extract, mutation records, property tax receipts, electricity bills.",
    docsRelationship: "Relationship proof",
    docsRelationshipDesc: "Birth certificate, marriage certificate, family tree (vansavali), school records — to prove you are a legal heir.",
    docsDeath: "Death-related papers",
    docsDeathDesc: "Death certificate of the person whose property is to be inherited, and a will (if any).",
    docsLegal: "Legal certificates",
    docsLegalDesc: "Legal heir certificate or succession certificate from the Tehsildar / Civil court — apply at your local revenue office.",
    docsTip: "Helpful tip",
    docsTipText: "Visit your nearest District Legal Services Authority (DLSA) — they help you get all these papers free of cost.",
    wizardIntro: "Answer 1–2 quick questions and we'll show only the documents you actually need.",
    wizardPickCase: "What is your situation?",
    wizardStep: "Step", wizardOf: "of", wizardNext: "Next", wizardPrev: "Back",
    wizardRestart: "Start over",
    wizardYourChecklist: "Your personal checklist",
    wizardWhyThis: "Why these documents?",
    wizardNextSteps: "What to do next",
    wizardAskChat: "Ask NyayaSakhi about this",
    wizardFindHelp: "Find legal help nearby",
    caseFatherTitle: "Father passed away — claiming his property",
    caseFatherDesc: "You want your share in your father's land, house or money.",
    caseHusbandTitle: "Husband passed away — claiming his property",
    caseHusbandDesc: "You want your share as a widow in his property.",
    caseDeniedTitle: "Brothers / family are denying my share",
    caseDeniedDesc: "Property exists but relatives won't give you your rightful share.",
    caseAgriTitle: "Agricultural land / village patta dispute",
    caseAgriDesc: "Issue is about farmland, patta, or revenue records.",
    qWillTitle: "Did the person leave a written will?",
    qWillYes: "Yes, there is a will", qWillNo: "No will", qWillUnknown: "I don't know",
    qReligionTitle: "What is the family's religion?",
    qHindu: "Hindu / Sikh / Jain / Buddhist", qMuslim: "Muslim", qChristian: "Christian", qOther: "Other",
    qLandTitle: "Is agricultural land involved?",
    qLandYes: "Yes", qLandNo: "No, only house / money / gold",
    stepWill: "Will", stepReligion: "Religion", stepLand: "Land type",
    nextFatherDLSA: "Visit your DLSA — apply for a Legal Heir Certificate (free).",
    nextFatherMutation: "Apply for mutation (dakhil-kharij) at the Tehsil office to add your name to land records.",
    nextFatherFIR: "If documents are hidden by relatives, file a written complaint at the police station and keep a copy.",
    nextHusbandSuccession: "Apply for a Succession Certificate at the Civil Court for bank accounts and movable property.",
    nextHusbandShare: "As a widow you are a Class I heir — you get an equal share with the children.",
    nextDeniedNotice: "Send a legal notice through a DLSA lawyer (free) demanding partition of the property.",
    nextDeniedSection6: "Daughters have equal rights since 2005 (Hindu Succession Act, Section 6) — quote this in your notice.",
    nextAgriPatta: "Get the latest 7/12 extract or patta from the village Patwari / Talati office.",
    nextAgriRevenue: "File a mutation request at the Tehsildar office; if denied, appeal to the SDM.",
  },
  hi: {
    tagline: "आपकी आवाज़। आपके अधिकार। आपकी विरासत।",
    subtitle: "ग्रामीण महिलाओं के लिए एक आसान, आवाज़-आधारित साथी — अपनी भाषा में विरासत के अधिकार समझें और मदद पाएँ।",
    heroCtaPrimary: "बात शुरू करें",
    heroCtaSecondary: "कानूनी मदद खोजें",
    heroCtaGuidance: "सरल कानूनी मार्गदर्शन",
    heroCtaUpload: "दस्तावेज़ समझें",
    docUpTitle: "दस्तावेज़ समझें",
    docUpSub: "कोई भी चिट्ठी, नोटिस या कागज़ का PDF या फोटो भेजें। हम सरल भाषा में समझाएँगे।",
    docUpChoose: "फ़ाइल चुनें",
    docUpMax: "अधिकतम 10 MB",
    docUpReading: "दस्तावेज़ पढ़ रही हूँ…",
    docUpThinking: "न्यायसखी सोच रही है…",
    docUpExplanation: "सरल समझ",
    docUpListen: "फिर से सुनें",
    docUpAnother: "दूसरा अपलोड करें",
    docUpTooBig: "फ़ाइल बहुत बड़ी है (अधिकतम 10 MB)।",
    docUpUnsupported: "कृपया PDF या फोटो भेजें।",
    docUpNoText: "इस फ़ाइल से कोई शब्द नहीं पढ़ पाई। साफ़ फोटो भेजें।",
    docUpExtractFail: "दस्तावेज़ नहीं पढ़ पाई। फिर से कोशिश करें।",
    chooseLanguage: "अपनी भाषा चुनें",
    chatPlaceholder: "लिखें या माइक दबाकर बोलें…",
    send: "भेजें", tapToSpeak: "बोलने के लिए दबाएँ", listening: "सुन रही हूँ…", speaking: "बोल रही हूँ…",
    directoryTitle: "पास की कानूनी मदद",
    directorySub: "नि:शुल्क कानूनी सहायता, NGO और महिला हेल्पलाइन।",
    selectState: "अपना राज्य चुनें", callNow: "अभी कॉल करें",
    lawyers: "कानूनी सहायता", ngos: "एनजीओ", helplines: "हेल्पलाइन",
    all: "सभी", search: "खोजें…", noResults: "कोई संपर्क नहीं मिला।",
    guidanceTitle: "आवाज़ चैटबॉट",
    guidanceSub: "विरासत के अधिकारों के बारे में कुछ भी पूछें।",
    disclaimer: "यह सामान्य जानकारी है, वकील का विकल्प नहीं।",
    back: "वापस",
    feature1Title: "अपनी भाषा में बात",
    feature1Desc: "12 भारतीय भाषाओं में आवाज़ से सवाल-जवाब।",
    feature2Title: "सरल कानूनी सलाह",
    feature2Desc: "आपका हिस्सा, बेटियों के अधिकार, और कानून — सरल भाषा में।",
    feature3Title: "पास में असली मदद",
    feature3Desc: "आपके राज्य की कानूनी सहायता और महिला हेल्पलाइन।",
    anonymous: "बिना लॉगिन जारी रखें",
    loginOptional: "मेरा मामला सुरक्षित रखें (वैकल्पिक)",
    forRuralWomen: "भारत की ग्रामीण महिलाओं के लिए · 12 भाषाएँ",
    talkingIn: "बात हो रही है",
    womenHelpline: "महिला हेल्पलाइन · 24×7",
    ctaTitle: "क्या आप अपने अधिकार जानने को तैयार हैं?",
    ctaDesc: "अपनी भाषा में बोलें। पढ़ने या लिखने की ज़रूरत नहीं। न्यायसखी सुनती है, जवाब देती है और पढ़कर सुनाती है।",
    footerNote: "भारत की महिलाओं के लिए प्यार से बनाया गया।",
    docsTitle: "ज़रूरी दस्तावेज़",
    docsSub: "विरासत और संपत्ति के मामलों में काम आने वाले काग़ज़ों की सरल सूची। नकलें संभालकर रखें।",
    docsIdentity: "पहचान प्रमाण",
    docsIdentityDesc: "आधार कार्ड, वोटर आईडी, पैन कार्ड, राशन कार्ड या पासपोर्ट — आपका और मृतक का।",
    docsProperty: "संपत्ति के दस्तावेज़",
    docsPropertyDesc: "बैनामा, दान-पत्र, पट्टा, 7/12 उतारा, दाखिल-खारिज, संपत्ति कर रसीद, बिजली बिल।",
    docsRelationship: "रिश्ते का प्रमाण",
    docsRelationshipDesc: "जन्म प्रमाण पत्र, विवाह प्रमाण पत्र, वंशावली, स्कूल के काग़ज़ — यह साबित करने के लिए कि आप उत्तराधिकारी हैं।",
    docsDeath: "मृत्यु से जुड़े काग़ज़",
    docsDeathDesc: "जिनकी संपत्ति है उनका मृत्यु प्रमाण पत्र, और वसीयत (यदि हो)।",
    docsLegal: "कानूनी प्रमाण पत्र",
    docsLegalDesc: "कानूनी वारिस प्रमाण पत्र या उत्तराधिकार प्रमाण पत्र — तहसीलदार / सिविल कोर्ट से, अपने राजस्व कार्यालय में आवेदन करें।",
    docsTip: "मददगार सुझाव",
    docsTipText: "अपने नज़दीकी जिला कानूनी सेवा प्राधिकरण (DLSA) जाएँ — वे ये सभी काग़ज़ नि:शुल्क बनवाने में मदद करते हैं।",
    wizardIntro: "1–2 छोटे सवालों के जवाब दें — हम सिर्फ़ ज़रूरी दस्तावेज़ ही दिखाएँगे।",
    wizardPickCase: "आपकी स्थिति क्या है?",
    wizardStep: "चरण", wizardOf: "में से", wizardNext: "आगे", wizardPrev: "पीछे",
    wizardRestart: "फिर से शुरू करें",
    wizardYourChecklist: "आपकी व्यक्तिगत सूची",
    wizardWhyThis: "ये दस्तावेज़ क्यों?",
    wizardNextSteps: "अब क्या करें",
    wizardAskChat: "न्यायसखी से इस बारे में पूछें",
    wizardFindHelp: "पास में कानूनी मदद खोजें",
    caseFatherTitle: "पिताजी का देहांत — उनकी संपत्ति में हिस्सा",
    caseFatherDesc: "आप अपने पिता की ज़मीन, घर या पैसे में अपना हिस्सा चाहती हैं।",
    caseHusbandTitle: "पति का देहांत — उनकी संपत्ति में हिस्सा",
    caseHusbandDesc: "विधवा के तौर पर पति की संपत्ति में हिस्सा चाहिए।",
    caseDeniedTitle: "भाई / परिवार हिस्सा देने से मना कर रहे हैं",
    caseDeniedDesc: "संपत्ति है लेकिन रिश्तेदार आपका हक़ नहीं दे रहे।",
    caseAgriTitle: "खेत / पट्टा / गाँव की ज़मीन का विवाद",
    caseAgriDesc: "मामला खेत की ज़मीन, पट्टे या राजस्व रिकॉर्ड का है।",
    qWillTitle: "क्या मरने वाले ने वसीयत लिखी थी?",
    qWillYes: "हाँ, वसीयत है", qWillNo: "वसीयत नहीं है", qWillUnknown: "मुझे नहीं पता",
    qReligionTitle: "परिवार का धर्म क्या है?",
    qHindu: "हिन्दू / सिख / जैन / बौद्ध", qMuslim: "मुस्लिम", qChristian: "ईसाई", qOther: "अन्य",
    qLandTitle: "क्या खेती की ज़मीन शामिल है?",
    qLandYes: "हाँ", qLandNo: "नहीं, सिर्फ़ घर / पैसे / सोना",
    stepWill: "वसीयत", stepReligion: "धर्म", stepLand: "ज़मीन का प्रकार",
    nextFatherDLSA: "अपने DLSA जाएँ — कानूनी वारिस प्रमाण पत्र के लिए नि:शुल्क आवेदन करें।",
    nextFatherMutation: "तहसील कार्यालय में दाखिल-खारिज के लिए आवेदन करें — ज़मीन के रिकॉर्ड में अपना नाम जुड़वाएँ।",
    nextFatherFIR: "अगर रिश्तेदार दस्तावेज़ छिपा रहे हैं, तो थाने में लिखित शिकायत दर्ज कराएँ और कॉपी रखें।",
    nextHusbandSuccession: "बैंक खाते और चल संपत्ति के लिए सिविल कोर्ट से उत्तराधिकार प्रमाण पत्र लें।",
    nextHusbandShare: "विधवा क्लास I उत्तराधिकारी हैं — बच्चों के बराबर हिस्सा मिलता है।",
    nextDeniedNotice: "DLSA के वकील से नि:शुल्क कानूनी नोटिस भिजवाएँ — संपत्ति के बँटवारे की माँग करें।",
    nextDeniedSection6: "2005 से बेटियों को बराबर हक़ है (हिन्दू उत्तराधिकार अधिनियम, धारा 6) — नोटिस में यह लिखें।",
    nextAgriPatta: "गाँव के पटवारी / तलाटी से ताज़ा 7/12 उतारा या पट्टा लें।",
    nextAgriRevenue: "तहसीलदार के यहाँ दाखिल-खारिज की अर्ज़ी दें; मना हो तो SDM के पास अपील करें।",
  },
  bn: {
    tagline: "আপনার কণ্ঠ। আপনার অধিকার। আপনার উত্তরাধিকার।",
    subtitle: "গ্রামীণ মহিলাদের জন্য একটি সহজ, কণ্ঠ-ভিত্তিক সাথী — নিজের ভাষায় উত্তরাধিকার অধিকার বুঝুন এবং সাহায্য পান।",
    heroCtaPrimary: "কথা শুরু করুন", heroCtaSecondary: "আইনি সাহায্য খুঁজুন", heroCtaGuidance: "সহজ আইনি দিকনির্দেশনা",
    chooseLanguage: "আপনার ভাষা বেছে নিন",
    chatPlaceholder: "লিখুন বা মাইকে চাপ দিয়ে বলুন…",
    send: "পাঠান", tapToSpeak: "বলতে চাপ দিন", listening: "শুনছি…", speaking: "বলছি…",
    directoryTitle: "কাছাকাছি আইনি সাহায্য",
    directorySub: "ভারত জুড়ে বিনামূল্যে আইনি সহায়তা, NGO ও মহিলা হেল্পলাইন।",
    selectState: "আপনার রাজ্য নির্বাচন করুন", callNow: "এখনই কল করুন",
    lawyers: "আইনি সহায়তা", ngos: "এনজিও", helplines: "হেল্পলাইন",
    all: "সব", search: "খুঁজুন…", noResults: "কোনো যোগাযোগ পাওয়া যায়নি।",
    guidanceTitle: "ভয়েস চ্যাটবট",
    guidanceSub: "উত্তরাধিকার অধিকার সম্পর্কে যেকোনো প্রশ্ন করুন।",
    disclaimer: "এটি সাধারণ তথ্য, আইনজীবীর বিকল্প নয়।",
    back: "ফিরে যান",
    feature1Title: "নিজের ভাষায় কথা",
    feature1Desc: "১২টি ভারতীয় ভাষায় কণ্ঠে প্রশ্ন ও উত্তর।",
    feature2Title: "সহজ আইনি পরামর্শ",
    feature2Desc: "আপনার অংশ, কন্যাদের অধিকার এবং আইন — সরল ভাষায়।",
    feature3Title: "কাছেই প্রকৃত মানুষের সাহায্য",
    feature3Desc: "আপনার রাজ্যের আইনি সহায়তা ও মহিলা হেল্পলাইন।",
    anonymous: "লগইন ছাড়াই চালিয়ে যান",
    forRuralWomen: "ভারতের গ্রামীণ মহিলাদের জন্য · ১২টি ভাষা",
    talkingIn: "কথা বলছি", womenHelpline: "মহিলা হেল্পলাইন · 24×7",
    ctaTitle: "আপনার অধিকার জানতে প্রস্তুত?",
    ctaDesc: "নিজের ভাষায় বলুন। পড়া বা লেখার দরকার নেই। ন্যায়সখী শোনে, উত্তর দেয় এবং পড়ে শোনায়।",
    footerNote: "ভারতের মহিলাদের জন্য ভালোবাসায় তৈরি।",
    docsTitle: "প্রয়োজনীয় কাগজপত্র",
    docsSub: "উত্তরাধিকার ও সম্পত্তি মামলায় কাজে আসা কাগজপত্রের সরল তালিকা। নকল নিরাপদে রাখুন।",
    docsIdentity: "পরিচয়পত্র",
    docsIdentityDesc: "আধার কার্ড, ভোটার আইডি, প্যান কার্ড, রেশন কার্ড বা পাসপোর্ট — আপনার এবং মৃত ব্যক্তির।",
    docsProperty: "সম্পত্তির কাগজ",
    docsPropertyDesc: "বিক্রয় দলিল, দান দলিল, পাট্টা, খতিয়ান, সম্পত্তি কর রসিদ, বিদ্যুৎ বিল।",
    docsRelationship: "সম্পর্কের প্রমাণ",
    docsRelationshipDesc: "জন্ম শংসাপত্র, বিবাহ শংসাপত্র, বংশতালিকা, স্কুলের কাগজ।",
    docsDeath: "মৃত্যু সংক্রান্ত কাগজ",
    docsDeathDesc: "মৃত্যু শংসাপত্র এবং উইল (যদি থাকে)।",
    docsLegal: "আইনি শংসাপত্র",
    docsLegalDesc: "আইনি উত্তরাধিকার শংসাপত্র — তহশিলদার বা সিভিল কোর্ট থেকে।",
    docsTip: "সহায়ক পরামর্শ",
    docsTipText: "নিকটতম জেলা আইনি পরিষেবা কর্তৃপক্ষ (DLSA)-এ যান — তারা বিনামূল্যে সাহায্য করেন।",
    wizardIntro: "১–২টি ছোট প্রশ্নের উত্তর দিন — আমরা শুধু আপনার প্রয়োজনীয় কাগজপত্র দেখাব।",
    wizardPickCase: "আপনার পরিস্থিতি কী?",
    wizardStep: "ধাপ", wizardOf: "এর", wizardNext: "পরবর্তী", wizardPrev: "পিছনে",
    wizardRestart: "আবার শুরু করুন",
    wizardYourChecklist: "আপনার ব্যক্তিগত তালিকা",
    wizardWhyThis: "কেন এই কাগজপত্র?",
    wizardNextSteps: "এরপর কী করবেন",
    wizardAskChat: "ন্যায়সখীকে এ বিষয়ে জিজ্ঞাসা করুন",
    wizardFindHelp: "কাছাকাছি আইনি সাহায্য খুঁজুন",
    caseFatherTitle: "বাবা মারা গেছেন — তাঁর সম্পত্তির দাবি",
    caseFatherDesc: "বাবার জমি, বাড়ি বা টাকায় আপনার অংশ চান।",
    caseHusbandTitle: "স্বামী মারা গেছেন — তাঁর সম্পত্তির দাবি",
    caseHusbandDesc: "বিধবা হিসাবে স্বামীর সম্পত্তিতে অংশ চান।",
    caseDeniedTitle: "ভাই / পরিবার আমার অংশ দিচ্ছে না",
    caseDeniedDesc: "সম্পত্তি আছে কিন্তু আত্মীয়রা ন্যায্য অংশ দিচ্ছে না।",
    caseAgriTitle: "কৃষি জমি / পাট্টা বিরোধ",
    caseAgriDesc: "চাষের জমি, পাট্টা বা রাজস্ব রেকর্ড সম্পর্কিত।",
    qWillTitle: "মৃত ব্যক্তি কি উইল রেখে গেছেন?",
    qWillYes: "হ্যাঁ, উইল আছে", qWillNo: "উইল নেই", qWillUnknown: "আমি জানি না",
    qReligionTitle: "পরিবারের ধর্ম কী?",
    qHindu: "হিন্দু / শিখ / জৈন / বৌদ্ধ", qMuslim: "মুসলিম", qChristian: "খ্রিস্টান", qOther: "অন্যান্য",
    qLandTitle: "কৃষি জমি কি জড়িত?",
    qLandYes: "হ্যাঁ", qLandNo: "না, শুধু বাড়ি / টাকা / সোনা",
    nextFatherDLSA: "DLSA-তে যান — আইনি উত্তরাধিকার শংসাপত্রের জন্য বিনামূল্যে আবেদন করুন।",
    nextFatherMutation: "তহশিল অফিসে নামজারির আবেদন করুন।",
    nextFatherFIR: "আত্মীয়রা কাগজ লুকালে থানায় লিখিত অভিযোগ দিন।",
    nextHusbandSuccession: "ব্যাংক ও অস্থাবর সম্পত্তির জন্য সিভিল কোর্ট থেকে উত্তরাধিকার শংসাপত্র নিন।",
    nextHusbandShare: "বিধবা হিসাবে আপনি Class I উত্তরাধিকারী — সন্তানদের সমান অংশ পাবেন।",
    nextDeniedNotice: "DLSA আইনজীবীর মাধ্যমে বিনামূল্যে আইনি নোটিশ পাঠান।",
    nextDeniedSection6: "২০০৫ সাল থেকে কন্যাদের সমান অধিকার (হিন্দু উত্তরাধিকার আইন, ধারা ৬)।",
    nextAgriPatta: "গ্রামের পাটোয়ারি থেকে সর্বশেষ খতিয়ান বা পাট্টা নিন।",
    nextAgriRevenue: "তহসিলদারের কাছে নামজারি আবেদন করুন; প্রত্যাখ্যাত হলে SDM-এর কাছে আপিল করুন।",
  },
  ta: {
    tagline: "உங்கள் குரல். உங்கள் உரிமைகள். உங்கள் வாரிசுரிமை.",
    subtitle: "கிராமப்புற பெண்களுக்கு ஒரு எளிய, குரல்-முதன்மை வழிகாட்டி — உங்கள் மொழியில் வாரிசுரிமைகளை புரிந்துகொண்டு உதவி பெறுங்கள்.",
    heroCtaPrimary: "பேசத் தொடங்குங்கள்", heroCtaSecondary: "சட்ட உதவியைக் கண்டறி", heroCtaGuidance: "எளிய சட்ட வழிகாட்டுதல்",
    chooseLanguage: "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
    chatPlaceholder: "எழுதவும் அல்லது மைக்கை அழுத்தவும்…",
    send: "அனுப்பு", tapToSpeak: "பேச அழுத்தவும்", listening: "கேட்கிறேன்…", speaking: "பேசுகிறேன்…",
    directoryTitle: "அருகிலுள்ள சட்ட உதவி",
    directorySub: "இந்தியா முழுவதும் இலவச சட்ட உதவி, NGO மற்றும் பெண்கள் ஹெல்ப்லைன்.",
    selectState: "உங்கள் மாநிலத்தைத் தேர்ந்தெடுக்கவும்", callNow: "இப்போது அழைக்கவும்",
    lawyers: "சட்ட உதவி", ngos: "என்ஜிஓ", helplines: "ஹெல்ப்லைன்",
    all: "அனைத்தும்", search: "தேடவும்…", noResults: "தொடர்புகள் எதுவும் இல்லை.",
    guidanceTitle: "குரல் சாட்போட்",
    guidanceSub: "உங்கள் வாரிசுரிமை குறித்து எதையும் கேளுங்கள்.",
    disclaimer: "இது பொது வழிகாட்டுதல், வழக்கறிஞருக்கு மாற்றாகாது.",
    back: "திரும்பு",
    feature1Title: "உங்கள் மொழியில் பேசுங்கள்",
    feature1Desc: "12 இந்திய மொழிகளில் குரலில் கேள்வி-பதில்.",
    feature2Title: "எளிய சட்ட வழிகாட்டுதல்",
    feature2Desc: "உங்கள் பங்கு, மகள்களின் உரிமைகள் மற்றும் சட்டம் — எளிய மொழியில்.",
    feature3Title: "அருகில் உண்மையான உதவி",
    feature3Desc: "உங்கள் மாநிலத்தின் சட்ட உதவி மற்றும் பெண்கள் ஹெல்ப்லைன்.",
    forRuralWomen: "இந்திய கிராமப்புற பெண்களுக்கு · 12 மொழிகள்",
    talkingIn: "பேசுகிறது", womenHelpline: "பெண்கள் ஹெல்ப்லைன் · 24×7",
    ctaTitle: "உங்கள் உரிமைகளை அறிய தயாரா?",
    ctaDesc: "உங்கள் மொழியில் பேசுங்கள். வாசிக்க தேவையில்லை. நியாயசகி கேட்கிறாள், பதில் சொல்கிறாள்.",
    footerNote: "இந்திய பெண்களுக்காக அன்புடன் உருவாக்கப்பட்டது.",
    docsTitle: "தேவையான ஆவணங்கள்",
    docsSub: "வாரிசுரிமை மற்றும் சொத்து வழக்குகளில் தேவைப்படும் ஆவணங்களின் எளிய பட்டியல்.",
    docsIdentity: "அடையாளச் சான்று",
    docsIdentityDesc: "ஆதார், வாக்காளர் அடையாள அட்டை, பான், ரேஷன் கார்டு அல்லது பாஸ்போர்ட்.",
    docsProperty: "சொத்து ஆவணங்கள்",
    docsPropertyDesc: "விற்பனை பத்திரம், தான பத்திரம், பட்டா, சொத்து வரி ரசீது, மின்சார பில்.",
    docsRelationship: "உறவு சான்று",
    docsRelationshipDesc: "பிறப்பு சான்றிதழ், திருமண சான்றிதழ், குடும்ப மரம், பள்ளி ஆவணங்கள்.",
    docsDeath: "மரணம் தொடர்பான ஆவணங்கள்",
    docsDeathDesc: "மரண சான்றிதழ் மற்றும் உயில் (இருந்தால்).",
    docsLegal: "சட்ட சான்றிதழ்கள்",
    docsLegalDesc: "சட்ட வாரிசு சான்றிதழ் — தாசில்தார் அல்லது சிவில் நீதிமன்றத்திலிருந்து.",
    docsTip: "உதவிக்குறிப்பு",
    docsTipText: "அருகிலுள்ள மாவட்ட சட்ட சேவைகள் ஆணையத்தை (DLSA) அணுகவும் — இலவசமாக உதவுவார்கள்.",
    wizardIntro: "1–2 சிறிய கேள்விகளுக்கு பதிலளியுங்கள் — தேவையான ஆவணங்களை மட்டும் காட்டுவோம்.",
    wizardPickCase: "உங்கள் நிலை என்ன?",
    wizardStep: "படி", wizardOf: "இல்", wizardNext: "அடுத்து", wizardPrev: "பின்",
    wizardRestart: "மீண்டும் தொடங்கு",
    wizardYourChecklist: "உங்கள் தனிப்பட்ட பட்டியல்",
    wizardWhyThis: "ஏன் இந்த ஆவணங்கள்?",
    wizardNextSteps: "அடுத்து என்ன செய்வது",
    wizardAskChat: "நியாயசகியிடம் கேளுங்கள்",
    wizardFindHelp: "அருகில் சட்ட உதவியை கண்டறி",
    caseFatherTitle: "தந்தை இறந்தார் — அவர் சொத்தில் பங்கு",
    caseFatherDesc: "தந்தையின் நிலம், வீடு அல்லது பணத்தில் உங்கள் பங்கு வேண்டும்.",
    caseHusbandTitle: "கணவர் இறந்தார் — அவர் சொத்தில் பங்கு",
    caseHusbandDesc: "விதவையாக கணவர் சொத்தில் பங்கு வேண்டும்.",
    caseDeniedTitle: "சகோதரர்கள் / குடும்பம் என் பங்கை மறுக்கின்றனர்",
    caseDeniedDesc: "சொத்து உள்ளது ஆனால் உரிமையை தர மறுக்கின்றனர்.",
    caseAgriTitle: "விவசாய நிலம் / பட்டா தகராறு",
    caseAgriDesc: "விவசாய நிலம், பட்டா அல்லது வருவாய் பதிவு பற்றியது.",
    qWillTitle: "இறந்தவர் உயில் எழுதியிருந்தாரா?",
    qWillYes: "ஆம், உயில் உள்ளது", qWillNo: "உயில் இல்லை", qWillUnknown: "தெரியாது",
    qReligionTitle: "குடும்பத்தின் மதம் என்ன?",
    qHindu: "இந்து / சீக்கியர் / சமணர் / பௌத்தர்", qMuslim: "முஸ்லிம்", qChristian: "கிறிஸ்தவர்", qOther: "மற்றவை",
    qLandTitle: "விவசாய நிலம் சம்பந்தப்பட்டதா?",
    qLandYes: "ஆம்", qLandNo: "இல்லை, வீடு / பணம் / தங்கம் மட்டும்",
    nextFatherDLSA: "DLSA-வை அணுகி சட்ட வாரிசு சான்றிதழுக்கு இலவசமாக விண்ணப்பிக்கவும்.",
    nextFatherMutation: "தாசில்தார் அலுவலகத்தில் பெயர் மாற்றத்திற்கு விண்ணப்பிக்கவும்.",
    nextFatherFIR: "உறவினர்கள் ஆவணங்களை மறைத்தால் காவல் நிலையத்தில் எழுத்துப்பூர்வ புகார் அளிக்கவும்.",
    nextHusbandSuccession: "வங்கி கணக்குகள் மற்றும் அசையும் சொத்துக்கான வாரிசு சான்றிதழைப் பெறுங்கள்.",
    nextHusbandShare: "விதவையாக நீங்கள் Class I வாரிசு — குழந்தைகளுக்கு சமமான பங்கு.",
    nextDeniedNotice: "DLSA வழக்கறிஞர் மூலம் இலவச சட்ட நோட்டீஸ் அனுப்பவும்.",
    nextDeniedSection6: "2005 முதல் மகள்களுக்கு சம உரிமை (இந்து வாரிசுரிமை சட்டம், பிரிவு 6).",
    nextAgriPatta: "கிராம பட்டாதார் / VAO-விடம் சமீபத்திய பட்டா பெறுங்கள்.",
    nextAgriRevenue: "தாசில்தாரிடம் பெயர் மாற்ற விண்ணப்பம்; மறுத்தால் SDM-க்கு மேல்முறையீடு.",
  },
  te: {
    tagline: "మీ గొంతు. మీ హక్కులు. మీ వారసత్వం.",
    subtitle: "గ్రామీణ మహిళల కోసం సరళమైన, గొంతు-ఆధారిత సహాయకుడు — మీ భాషలో వారసత్వ హక్కులను తెలుసుకోండి.",
    heroCtaPrimary: "మాట్లాడటం ప్రారంభించండి", heroCtaSecondary: "న్యాయ సహాయం", heroCtaGuidance: "సరళ న్యాయ మార్గదర్శనం",
    chooseLanguage: "మీ భాషను ఎంచుకోండి",
    chatPlaceholder: "టైప్ చేయండి లేదా మైక్ నొక్కండి…",
    send: "పంపు", tapToSpeak: "మాట్లాడటానికి నొక్కండి", listening: "వింటున్నాను…", speaking: "మాట్లాడుతున్నాను…",
    directoryTitle: "సమీపంలోని న్యాయ సహాయం",
    directorySub: "భారతదేశం అంతటా ఉచిత న్యాయ సహాయం, NGOలు మరియు హెల్ప్‌లైన్‌లు.",
    selectState: "మీ రాష్ట్రాన్ని ఎంచుకోండి", callNow: "ఇప్పుడు కాల్ చేయండి",
    lawyers: "న్యాయ సహాయం", ngos: "ఎన్జీఓ", helplines: "హెల్ప్‌లైన్",
    all: "అన్నీ", search: "వెతకండి…", noResults: "పరిచయాలు లేవు.",
    guidanceTitle: "వాయిస్ చాట్‌బాట్",
    guidanceSub: "మీ వారసత్వ హక్కుల గురించి ఏదైనా అడగండి.",
    disclaimer: "ఇది సాధారణ సమాచారం, న్యాయవాదికి ప్రత్యామ్నాయం కాదు.",
    back: "వెనక్కి",
    feature1Title: "మీ భాషలో మాట్లాడండి",
    feature1Desc: "12 భారతీయ భాషల్లో వాయిస్ ప్రశ్న-జవాబు.",
    feature2Title: "సరళ న్యాయ సలహా",
    feature2Desc: "మీ వాటా, కుమార్తెల హక్కులు మరియు చట్టం — సరళంగా.",
    feature3Title: "సమీపంలో నిజమైన సహాయం",
    feature3Desc: "మీ రాష్ట్రంలో న్యాయ సహాయం మరియు మహిళా హెల్ప్‌లైన్.",
    forRuralWomen: "భారత గ్రామీణ మహిళల కోసం · 12 భాషలు",
    talkingIn: "మాట్లాడుతోంది", womenHelpline: "మహిళా హెల్ప్‌లైన్ · 24×7",
    ctaTitle: "మీ హక్కులు తెలుసుకోవడానికి సిద్ధమా?",
    ctaDesc: "మీ భాషలో మాట్లాడండి. చదవాల్సిన అవసరం లేదు. న్యాయసఖి వింటుంది, జవాబిస్తుంది.",
    footerNote: "భారత మహిళల కోసం ప్రేమతో తయారు చేయబడింది.",
    docsTitle: "అవసరమైన పత్రాలు",
    docsSub: "వారసత్వ మరియు ఆస్తి కేసుల్లో పనికొచ్చే పత్రాల జాబితా.",
    docsIdentity: "గుర్తింపు రుజువు",
    docsIdentityDesc: "ఆధార్, ఓటర్ ID, పాన్, రేషన్ కార్డ్ లేదా పాస్‌పోర్ట్.",
    docsProperty: "ఆస్తి పత్రాలు",
    docsPropertyDesc: "విక్రయ పత్రం, దాన పత్రం, పట్టా, ఆస్తి పన్ను రసీదు, విద్యుత్ బిల్లు.",
    docsRelationship: "సంబంధ రుజువు",
    docsRelationshipDesc: "జనన ధృవీకరణ పత్రం, వివాహ ధృవీకరణ పత్రం, వంశవృక్షం.",
    docsDeath: "మరణ సంబంధిత పత్రాలు",
    docsDeathDesc: "మరణ ధృవీకరణ పత్రం మరియు వీలునామా (ఉంటే).",
    docsLegal: "న్యాయ ధృవీకరణ పత్రాలు",
    docsLegalDesc: "న్యాయ వారసత్వ ధృవీకరణ పత్రం — తహసీల్దార్ లేదా సివిల్ కోర్టు నుండి.",
    docsTip: "సహాయక సూచన",
    docsTipText: "సమీపంలోని జిల్లా న్యాయ సేవల అధికారానికి (DLSA) వెళ్లండి — ఉచితంగా సహాయం చేస్తారు.",
    wizardIntro: "1–2 చిన్న ప్రశ్నలకు సమాధానం ఇవ్వండి — మీకు అవసరమైన పత్రాలను మాత్రమే చూపిస్తాము.",
    wizardPickCase: "మీ పరిస్థితి ఏమిటి?",
    wizardStep: "దశ", wizardOf: "లో", wizardNext: "తరువాత", wizardPrev: "వెనక్కి",
    wizardRestart: "మళ్లీ ప్రారంభించండి",
    wizardYourChecklist: "మీ వ్యక్తిగత జాబితా",
    wizardWhyThis: "ఈ పత్రాలు ఎందుకు?",
    wizardNextSteps: "తరువాత ఏమి చేయాలి",
    wizardAskChat: "న్యాయసఖిని అడగండి",
    wizardFindHelp: "సమీపంలో న్యాయ సహాయం",
    caseFatherTitle: "తండ్రి మరణించారు — వారి ఆస్తిలో వాటా",
    caseFatherDesc: "తండ్రి భూమి, ఇల్లు లేదా డబ్బులో మీ వాటా కావాలి.",
    caseHusbandTitle: "భర్త మరణించారు — వారి ఆస్తిలో వాటా",
    caseHusbandDesc: "విధవరాలిగా భర్త ఆస్తిలో వాటా కావాలి.",
    caseDeniedTitle: "సోదరులు / కుటుంబం నా వాటాను నిరాకరిస్తున్నారు",
    caseDeniedDesc: "ఆస్తి ఉంది కానీ బంధువులు హక్కు ఇవ్వడం లేదు.",
    caseAgriTitle: "వ్యవసాయ భూమి / పట్టా వివాదం",
    caseAgriDesc: "వ్యవసాయ భూమి, పట్టా లేదా రెవెన్యూ రికార్డు గురించి.",
    qWillTitle: "మరణించిన వ్యక్తి వీలునామా రాశారా?",
    qWillYes: "అవును, వీలునామా ఉంది", qWillNo: "వీలునామా లేదు", qWillUnknown: "నాకు తెలియదు",
    qReligionTitle: "కుటుంబ మతం ఏమిటి?",
    qHindu: "హిందూ / సిక్కు / జైన / బౌద్ధ", qMuslim: "ముస్లిం", qChristian: "క్రైస్తవ", qOther: "ఇతర",
    qLandTitle: "వ్యవసాయ భూమి ఉందా?",
    qLandYes: "అవును", qLandNo: "లేదు, ఇల్లు / డబ్బు / బంగారం మాత్రమే",
    nextFatherDLSA: "DLSAని సందర్శించి న్యాయ వారసత్వ ధృవీకరణ పత్రం కోసం ఉచితంగా దరఖాస్తు చేయండి.",
    nextFatherMutation: "తహసీల్దార్ కార్యాలయంలో మ్యుటేషన్ కోసం దరఖాస్తు చేయండి.",
    nextFatherFIR: "బంధువులు పత్రాలు దాచిపెడితే పోలీస్ స్టేషన్‌లో వ్రాతపూర్వక ఫిర్యాదు ఇవ్వండి.",
    nextHusbandSuccession: "బ్యాంకు ఖాతాలు, చర ఆస్తి కోసం సివిల్ కోర్టు నుండి వారసత్వ ధృవీకరణ పత్రం పొందండి.",
    nextHusbandShare: "విధవరాలిగా మీరు Class I వారసురాలు — పిల్లలతో సమాన వాటా.",
    nextDeniedNotice: "DLSA న్యాయవాది ద్వారా ఉచిత న్యాయ నోటీసు పంపండి.",
    nextDeniedSection6: "2005 నుండి కుమార్తెలకు సమాన హక్కులు (హిందూ వారసత్వ చట్టం, సెక్షన్ 6).",
    nextAgriPatta: "గ్రామ పట్వారీ నుండి తాజా పట్టా పొందండి.",
    nextAgriRevenue: "తహసీల్దార్‌కి మ్యుటేషన్ దరఖాస్తు; తిరస్కరిస్తే SDM-కి అప్పీల్.",
  },
  mr: {
    tagline: "तुमचा आवाज. तुमचे हक्क. तुमचा वारसा.",
    subtitle: "ग्रामीण महिलांसाठी सोपा, आवाज-आधारित सहाय्यक — तुमच्या भाषेत वारसा हक्क समजून घ्या.",
    heroCtaPrimary: "बोलायला सुरुवात करा", heroCtaSecondary: "कायदेशीर मदत शोधा", heroCtaGuidance: "सोपे कायदेशीर मार्गदर्शन",
    chooseLanguage: "तुमची भाषा निवडा",
    chatPlaceholder: "टाइप करा किंवा माइक दाबा…",
    send: "पाठवा", tapToSpeak: "बोलण्यासाठी दाबा", listening: "ऐकत आहे…", speaking: "बोलत आहे…",
    directoryTitle: "जवळची कायदेशीर मदत",
    directorySub: "मोफत कायदेशीर सहाय्य, NGO आणि महिला हेल्पलाइन.",
    selectState: "तुमचे राज्य निवडा", callNow: "आता कॉल करा",
    lawyers: "कायदेशीर सहाय्य", ngos: "एनजीओ", helplines: "हेल्पलाइन",
    all: "सर्व", search: "शोधा…", noResults: "संपर्क सापडले नाहीत.",
    guidanceTitle: "व्हॉइस चॅटबॉट",
    guidanceSub: "वारसा हक्कांबद्दल काहीही विचारा.",
    disclaimer: "ही सामान्य माहिती आहे, वकिलाचा पर्याय नाही.",
    back: "मागे",
    feature1Title: "तुमच्या भाषेत बोला", feature1Desc: "12 भारतीय भाषांत आवाजाने प्रश्न-उत्तर.",
    feature2Title: "सोपा कायदेशीर सल्ला", feature2Desc: "तुमचा हिस्सा, मुलींचे हक्क आणि कायदा — सोप्या भाषेत.",
    feature3Title: "जवळच खरी मदत", feature3Desc: "तुमच्या राज्यातील कायदेशीर मदत आणि महिला हेल्पलाइन.",
    forRuralWomen: "भारतातील ग्रामीण महिलांसाठी · 12 भाषा",
    talkingIn: "बोलत आहे", womenHelpline: "महिला हेल्पलाइन · 24×7",
    ctaTitle: "तुमचे हक्क जाणून घ्यायला तयार?",
    ctaDesc: "तुमच्या भाषेत बोला. वाचायची गरज नाही. न्यायसखी ऐकते, उत्तर देते.",
    footerNote: "भारतातील महिलांसाठी प्रेमाने बनवले.",
    docsTitle: "आवश्यक कागदपत्रे", docsSub: "वारसा आणि मालमत्ता प्रकरणांत उपयोगी कागदपत्रांची सोपी यादी.",
    docsIdentity: "ओळख पुरावा", docsIdentityDesc: "आधार, मतदार ओळखपत्र, पॅन, शिधापत्रिका किंवा पासपोर्ट.",
    docsProperty: "मालमत्तेची कागदपत्रे", docsPropertyDesc: "खरेदीखत, दानपत्र, पट्टा, 7/12 उतारा, मालमत्ता कर पावती.",
    docsRelationship: "नात्याचा पुरावा", docsRelationshipDesc: "जन्म दाखला, विवाह दाखला, वंशावळी, शाळेची कागदपत्रे.",
    docsDeath: "मृत्यूशी संबंधित कागद", docsDeathDesc: "मृत्यू प्रमाणपत्र आणि मृत्यूपत्र (असल्यास).",
    docsLegal: "कायदेशीर प्रमाणपत्रे", docsLegalDesc: "वारसा प्रमाणपत्र — तहसीलदार किंवा दिवाणी न्यायालयाकडून.",
    docsTip: "उपयुक्त टीप", docsTipText: "जवळच्या जिल्हा कायदेशीर सेवा प्राधिकरणाला (DLSA) भेट द्या — मोफत मदत करतात.",
    wizardIntro: "1–2 छोट्या प्रश्नांची उत्तरे द्या — आम्ही फक्त तुम्हाला लागणारी कागदपत्रे दाखवू.",
    wizardPickCase: "तुमची परिस्थिती काय आहे?",
    wizardStep: "टप्पा", wizardOf: "पैकी", wizardNext: "पुढे", wizardPrev: "मागे",
    wizardRestart: "पुन्हा सुरू करा",
    wizardYourChecklist: "तुमची वैयक्तिक यादी",
    wizardWhyThis: "ही कागदपत्रे का?",
    wizardNextSteps: "पुढे काय करायचे",
    wizardAskChat: "न्यायसखीला विचारा",
    wizardFindHelp: "जवळची कायदेशीर मदत शोधा",
    caseFatherTitle: "वडिलांचे निधन — त्यांच्या मालमत्तेत वाटा",
    caseFatherDesc: "वडिलांच्या जमीन, घर किंवा पैशांत तुमचा वाटा हवा.",
    caseHusbandTitle: "पतीचे निधन — त्यांच्या मालमत्तेत वाटा",
    caseHusbandDesc: "विधवा म्हणून पतीच्या मालमत्तेत वाटा हवा.",
    caseDeniedTitle: "भाऊ / कुटुंब वाटा देत नाहीत",
    caseDeniedDesc: "मालमत्ता आहे पण नातेवाईक हक्क देत नाहीत.",
    caseAgriTitle: "शेतजमीन / पट्टा वाद",
    caseAgriDesc: "शेती, पट्टा किंवा महसूल नोंदींबद्दल.",
    qWillTitle: "मृत व्यक्तीने मृत्युपत्र लिहिले होते का?",
    qWillYes: "होय, मृत्युपत्र आहे", qWillNo: "मृत्युपत्र नाही", qWillUnknown: "मला माहीत नाही",
    qReligionTitle: "कुटुंबाचा धर्म कोणता?",
    qHindu: "हिंदू / शीख / जैन / बौद्ध", qMuslim: "मुस्लिम", qChristian: "ख्रिश्चन", qOther: "इतर",
    qLandTitle: "शेतजमीन गुंतलेली आहे का?",
    qLandYes: "होय", qLandNo: "नाही, फक्त घर / पैसे / सोने",
    nextFatherDLSA: "DLSA ला भेट द्या — कायदेशीर वारस प्रमाणपत्रासाठी मोफत अर्ज करा.",
    nextFatherMutation: "तहसील कार्यालयात फेरफारसाठी अर्ज करा.",
    nextFatherFIR: "नातेवाईक कागद लपवत असतील तर पोलीस ठाण्यात लेखी तक्रार द्या.",
    nextHusbandSuccession: "बँक खाते आणि जंगम मालमत्तेसाठी दिवाणी न्यायालयातून वारसा प्रमाणपत्र घ्या.",
    nextHusbandShare: "विधवा म्हणून तुम्ही Class I वारस आहात — मुलांच्या समान वाटा.",
    nextDeniedNotice: "DLSA वकिलामार्फत मोफत कायदेशीर नोटीस पाठवा.",
    nextDeniedSection6: "2005 पासून मुलींना समान हक्क (हिंदू वारसा कायदा, कलम 6).",
    nextAgriPatta: "गावच्या तलाठ्याकडून ताजा 7/12 उतारा घ्या.",
    nextAgriRevenue: "तहसीलदाराकडे फेरफार अर्ज; नकार दिल्यास SDM कडे अपील.",
  },
  gu: {
    tagline: "તમારો અવાજ. તમારા હક્કો. તમારી વારસાગતિ.",
    subtitle: "ગ્રામીણ મહિલાઓ માટે સરળ, અવાજ-આધારિત સહાયક — તમારી ભાષામાં વારસા હક્કો સમજો.",
    heroCtaPrimary: "વાત શરૂ કરો", heroCtaSecondary: "કાનૂની મદદ શોધો", heroCtaGuidance: "સરળ કાનૂની માર્ગદર્શન",
    chooseLanguage: "તમારી ભાષા પસંદ કરો",
    chatPlaceholder: "લખો અથવા માઇક દબાવો…",
    send: "મોકલો", tapToSpeak: "બોલવા માટે દબાવો", listening: "સાંભળું છું…", speaking: "બોલું છું…",
    directoryTitle: "નજીકની કાનૂની મદદ",
    directorySub: "મફત કાનૂની સહાય, NGO અને મહિલા હેલ્પલાઇન.",
    selectState: "તમારું રાજ્ય પસંદ કરો", callNow: "હમણાં કૉલ કરો",
    lawyers: "કાનૂની સહાય", ngos: "એનજીઓ", helplines: "હેલ્પલાઇન",
    all: "બધા", search: "શોધો…", noResults: "કોઈ સંપર્ક મળ્યા નહીં.",
    guidanceTitle: "વૉઇસ ચેટબૉટ", guidanceSub: "તમારા વારસા હક્કો વિશે કંઈપણ પૂછો.",
    disclaimer: "આ સામાન્ય માહિતી છે, વકીલનો વિકલ્પ નથી.", back: "પાછા",
    feature1Title: "તમારી ભાષામાં વાત", feature1Desc: "12 ભારતીય ભાષાઓમાં અવાજથી પ્રશ્ન-જવાબ.",
    feature2Title: "સરળ કાનૂની સલાહ", feature2Desc: "તમારો હિસ્સો, દીકરીઓના હક્કો અને કાયદો — સરળ ભાષામાં.",
    feature3Title: "નજીકમાં ખરી મદદ", feature3Desc: "તમારા રાજ્યની કાનૂની સહાય અને મહિલા હેલ્પલાઇન.",
    forRuralWomen: "ભારતની ગ્રામીણ મહિલાઓ માટે · 12 ભાષાઓ",
    talkingIn: "વાત ચાલે છે", womenHelpline: "મહિલા હેલ્પલાઇન · 24×7",
    ctaTitle: "તમારા હક્કો જાણવા તૈયાર?",
    ctaDesc: "તમારી ભાષામાં બોલો. વાંચવાની જરૂર નથી. ન્યાયસખી સાંભળે છે, જવાબ આપે છે.",
    footerNote: "ભારતની મહિલાઓ માટે પ્રેમથી બનાવ્યું.",
    docsTitle: "જરૂરી દસ્તાવેજો", docsSub: "વારસા અને મિલકતના કેસોમાં કામ આવતા કાગળોની યાદી.",
    docsIdentity: "ઓળખનો પુરાવો", docsIdentityDesc: "આધાર, મતદાર ID, પાન, રેશન કાર્ડ અથવા પાસપોર્ટ.",
    docsProperty: "મિલકતના દસ્તાવેજો", docsPropertyDesc: "વેચાણ ખત, દાન ખત, પટ્ટો, મિલકત કર રસીદ, વીજળી બિલ.",
    docsRelationship: "સંબંધનો પુરાવો", docsRelationshipDesc: "જન્મ પ્રમાણપત્ર, લગ્ન પ્રમાણપત્ર, વંશાવળી.",
    docsDeath: "મૃત્યુ સંબંધિત કાગળો", docsDeathDesc: "મૃત્યુ પ્રમાણપત્ર અને વસિયતનામું (જો હોય).",
    docsLegal: "કાનૂની પ્રમાણપત્રો", docsLegalDesc: "કાનૂની વારસ પ્રમાણપત્ર — તહસીલદાર અથવા સિવિલ કોર્ટથી.",
    docsTip: "ઉપયોગી ટિપ", docsTipText: "નજીકના જિલ્લા કાનૂની સેવા સત્તામંડળ (DLSA)ની મુલાકાત લો — મફત મદદ.",
    wizardIntro: "1–2 નાના પ્રશ્નોના જવાબ આપો — અમે ફક્ત તમને જરૂરી દસ્તાવેજો બતાવીશું.",
    wizardPickCase: "તમારી પરિસ્થિતિ શું છે?",
    wizardStep: "પગલું", wizardOf: "માંથી", wizardNext: "આગળ", wizardPrev: "પાછળ",
    wizardRestart: "ફરીથી શરૂ કરો",
    wizardYourChecklist: "તમારી વ્યક્તિગત યાદી",
    wizardWhyThis: "આ દસ્તાવેજો કેમ?",
    wizardNextSteps: "હવે શું કરવું",
    wizardAskChat: "ન્યાયસખીને પૂછો",
    wizardFindHelp: "નજીકમાં કાનૂની મદદ શોધો",
    caseFatherTitle: "પિતાનું અવસાન — તેમની મિલકતમાં હિસ્સો",
    caseFatherDesc: "પિતાની જમીન, ઘર કે પૈસામાં તમારો હિસ્સો જોઈએ.",
    caseHusbandTitle: "પતિનું અવસાન — તેમની મિલકતમાં હિસ્સો",
    caseHusbandDesc: "વિધવા તરીકે પતિની મિલકતમાં હિસ્સો જોઈએ.",
    caseDeniedTitle: "ભાઈઓ / કુટુંબ મારો હિસ્સો આપતા નથી",
    caseDeniedDesc: "મિલકત છે પણ સગાઓ હક્ક આપતા નથી.",
    caseAgriTitle: "ખેતીની જમીન / પટ્ટા વિવાદ",
    caseAgriDesc: "ખેતી, પટ્ટા કે મહેસૂલ રેકોર્ડ વિશે.",
    qWillTitle: "મૃત વ્યક્તિએ વસિયત લખી હતી?",
    qWillYes: "હા, વસિયત છે", qWillNo: "વસિયત નથી", qWillUnknown: "મને ખબર નથી",
    qReligionTitle: "પરિવારનો ધર્મ કયો છે?",
    qHindu: "હિન્દુ / શીખ / જૈન / બૌદ્ધ", qMuslim: "મુસ્લિમ", qChristian: "ખ્રિસ્તી", qOther: "અન્ય",
    qLandTitle: "ખેતીની જમીન સામેલ છે?",
    qLandYes: "હા", qLandNo: "ના, ફક્ત ઘર / પૈસા / સોનું",
    nextFatherDLSA: "DLSA ની મુલાકાત લો — કાનૂની વારસ પ્રમાણપત્ર માટે મફત અરજી કરો.",
    nextFatherMutation: "તહસીલ ઑફિસમાં નામ ફેરફાર માટે અરજી કરો.",
    nextFatherFIR: "સગાઓ કાગળ છુપાવે તો પોલીસ સ્ટેશનમાં લેખિત ફરિયાદ આપો.",
    nextHusbandSuccession: "બેંક ખાતા અને જંગમ મિલકત માટે સિવિલ કોર્ટથી વારસા પ્રમાણપત્ર લો.",
    nextHusbandShare: "વિધવા તરીકે તમે Class I વારસ છો — બાળકો સાથે સમાન હિસ્સો.",
    nextDeniedNotice: "DLSA વકીલ મારફતે મફત કાનૂની નોટિસ મોકલો.",
    nextDeniedSection6: "2005 થી દીકરીઓને સમાન હક્ક (હિન્દુ વારસા કાયદો, કલમ 6).",
    nextAgriPatta: "ગામના તલાટી પાસેથી તાજો 7/12 ઉતારો લો.",
    nextAgriRevenue: "તહસીલદાર પાસે નામ ફેરફાર અરજી; નકાર થાય તો SDM ને અપીલ.",
  },
  kn: {
    tagline: "ನಿಮ್ಮ ಧ್ವನಿ. ನಿಮ್ಮ ಹಕ್ಕುಗಳು. ನಿಮ್ಮ ಪಿತ್ರಾರ್ಜಿತ.",
    subtitle: "ಗ್ರಾಮೀಣ ಮಹಿಳೆಯರಿಗೆ ಸರಳ ಧ್ವನಿ-ಆಧಾರಿತ ಸಹಾಯಕ — ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಪಿತ್ರಾರ್ಜಿತ ಹಕ್ಕುಗಳನ್ನು ಅರ್ಥಮಾಡಿಕೊಳ್ಳಿ.",
    heroCtaPrimary: "ಮಾತನಾಡಲು ಪ್ರಾರಂಭಿಸಿ", heroCtaSecondary: "ಕಾನೂನು ಸಹಾಯ", heroCtaGuidance: "ಸರಳ ಕಾನೂನು ಮಾರ್ಗದರ್ಶನ",
    chooseLanguage: "ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    chatPlaceholder: "ಟೈಪ್ ಮಾಡಿ ಅಥವಾ ಮೈಕ್ ಒತ್ತಿ…",
    send: "ಕಳುಹಿಸಿ", tapToSpeak: "ಮಾತನಾಡಲು ಒತ್ತಿ", listening: "ಕೇಳುತ್ತಿದ್ದೇನೆ…", speaking: "ಮಾತನಾಡುತ್ತಿದ್ದೇನೆ…",
    directoryTitle: "ಹತ್ತಿರದ ಕಾನೂನು ಸಹಾಯ",
    directorySub: "ಭಾರತದಾದ್ಯಂತ ಉಚಿತ ಕಾನೂನು ಸಹಾಯ, NGO ಮತ್ತು ಮಹಿಳಾ ಸಹಾಯವಾಣಿ.",
    selectState: "ನಿಮ್ಮ ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ", callNow: "ಈಗ ಕರೆ ಮಾಡಿ",
    lawyers: "ಕಾನೂನು ಸಹಾಯ", ngos: "ಎನ್‌ಜಿಒ", helplines: "ಸಹಾಯವಾಣಿ",
    all: "ಎಲ್ಲಾ", search: "ಹುಡುಕಿ…", noResults: "ಯಾವುದೇ ಸಂಪರ್ಕಗಳಿಲ್ಲ.",
    guidanceTitle: "ಧ್ವನಿ ಚಾಟ್‌ಬಾಟ್", guidanceSub: "ನಿಮ್ಮ ಪಿತ್ರಾರ್ಜಿತ ಹಕ್ಕುಗಳ ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ.",
    disclaimer: "ಇದು ಸಾಮಾನ್ಯ ಮಾಹಿತಿ, ವಕೀಲರಿಗೆ ಬದಲಿ ಅಲ್ಲ.", back: "ಹಿಂದೆ",
    feature1Title: "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ", feature1Desc: "12 ಭಾರತೀಯ ಭಾಷೆಗಳಲ್ಲಿ ಧ್ವನಿಯಲ್ಲಿ ಪ್ರಶ್ನೆ-ಉತ್ತರ.",
    feature2Title: "ಸರಳ ಕಾನೂನು ಸಲಹೆ", feature2Desc: "ನಿಮ್ಮ ಪಾಲು, ಹೆಣ್ಣುಮಕ್ಕಳ ಹಕ್ಕುಗಳು ಮತ್ತು ಕಾನೂನು — ಸರಳವಾಗಿ.",
    feature3Title: "ಹತ್ತಿರ ನಿಜವಾದ ಸಹಾಯ", feature3Desc: "ನಿಮ್ಮ ರಾಜ್ಯದ ಕಾನೂನು ಸಹಾಯ ಮತ್ತು ಮಹಿಳಾ ಸಹಾಯವಾಣಿ.",
    forRuralWomen: "ಭಾರತದ ಗ್ರಾಮೀಣ ಮಹಿಳೆಯರಿಗೆ · 12 ಭಾಷೆಗಳು",
    talkingIn: "ಮಾತನಾಡುತ್ತಿದೆ", womenHelpline: "ಮಹಿಳಾ ಸಹಾಯವಾಣಿ · 24×7",
    ctaTitle: "ನಿಮ್ಮ ಹಕ್ಕುಗಳನ್ನು ತಿಳಿಯಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
    ctaDesc: "ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಮಾತನಾಡಿ. ಓದುವ ಅಗತ್ಯವಿಲ್ಲ. ನ್ಯಾಯಸಖಿ ಕೇಳುತ್ತಾಳೆ, ಉತ್ತರಿಸುತ್ತಾಳೆ.",
    footerNote: "ಭಾರತದ ಮಹಿಳೆಯರಿಗಾಗಿ ಪ್ರೀತಿಯಿಂದ ತಯಾರಿಸಲಾಗಿದೆ.",
    docsTitle: "ಬೇಕಾದ ದಾಖಲೆಗಳು", docsSub: "ಪಿತ್ರಾರ್ಜಿತ ಮತ್ತು ಆಸ್ತಿ ಪ್ರಕರಣಗಳಲ್ಲಿ ಬೇಕಾಗುವ ದಾಖಲೆಗಳ ಪಟ್ಟಿ.",
    docsIdentity: "ಗುರುತಿನ ಪುರಾವೆ", docsIdentityDesc: "ಆಧಾರ್, ಮತದಾರರ ಗುರುತಿನ ಚೀಟಿ, ಪ್ಯಾನ್, ಪಡಿತರ ಚೀಟಿ ಅಥವಾ ಪಾಸ್‌ಪೋರ್ಟ್.",
    docsProperty: "ಆಸ್ತಿ ದಾಖಲೆಗಳು", docsPropertyDesc: "ಮಾರಾಟ ಪತ್ರ, ದಾನ ಪತ್ರ, ಪಟ್ಟಾ, ಆಸ್ತಿ ತೆರಿಗೆ ರಸೀದಿ, ವಿದ್ಯುತ್ ಬಿಲ್.",
    docsRelationship: "ಸಂಬಂಧದ ಪುರಾವೆ", docsRelationshipDesc: "ಜನನ ಪ್ರಮಾಣಪತ್ರ, ವಿವಾಹ ಪ್ರಮಾಣಪತ್ರ, ವಂಶವೃಕ್ಷ.",
    docsDeath: "ಮರಣ ಸಂಬಂಧಿತ ದಾಖಲೆ", docsDeathDesc: "ಮರಣ ಪ್ರಮಾಣಪತ್ರ ಮತ್ತು ಮರಣ ಪತ್ರ (ಇದ್ದರೆ).",
    docsLegal: "ಕಾನೂನು ಪ್ರಮಾಣಪತ್ರಗಳು", docsLegalDesc: "ಕಾನೂನು ಉತ್ತರಾಧಿಕಾರ ಪ್ರಮಾಣಪತ್ರ — ತಹಶೀಲ್ದಾರ್ ಅಥವಾ ಸಿವಿಲ್ ನ್ಯಾಯಾಲಯದಿಂದ.",
    docsTip: "ಸಹಾಯಕ ಸಲಹೆ", docsTipText: "ಹತ್ತಿರದ ಜಿಲ್ಲಾ ಕಾನೂನು ಸೇವೆಗಳ ಪ್ರಾಧಿಕಾರಕ್ಕೆ (DLSA) ಭೇಟಿ ನೀಡಿ — ಉಚಿತ ಸಹಾಯ.",
    wizardIntro: "1–2 ಸಣ್ಣ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ — ನಿಮಗೆ ಬೇಕಾದ ದಾಖಲೆಗಳನ್ನು ಮಾತ್ರ ತೋರಿಸುತ್ತೇವೆ.",
    wizardPickCase: "ನಿಮ್ಮ ಪರಿಸ್ಥಿತಿ ಏನು?",
    wizardStep: "ಹಂತ", wizardOf: "ರಲ್ಲಿ", wizardNext: "ಮುಂದೆ", wizardPrev: "ಹಿಂದೆ",
    wizardRestart: "ಮತ್ತೆ ಪ್ರಾರಂಭಿಸಿ",
    wizardYourChecklist: "ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಪಟ್ಟಿ",
    wizardWhyThis: "ಈ ದಾಖಲೆಗಳು ಏಕೆ?",
    wizardNextSteps: "ಮುಂದೆ ಏನು ಮಾಡಬೇಕು",
    wizardAskChat: "ನ್ಯಾಯಸಖಿಯನ್ನು ಕೇಳಿ",
    wizardFindHelp: "ಹತ್ತಿರ ಕಾನೂನು ಸಹಾಯ ಹುಡುಕಿ",
    caseFatherTitle: "ತಂದೆ ಮರಣ — ಅವರ ಆಸ್ತಿಯಲ್ಲಿ ಪಾಲು",
    caseFatherDesc: "ತಂದೆಯ ಭೂಮಿ, ಮನೆ ಅಥವಾ ಹಣದಲ್ಲಿ ನಿಮ್ಮ ಪಾಲು ಬೇಕು.",
    caseHusbandTitle: "ಪತಿ ಮರಣ — ಅವರ ಆಸ್ತಿಯಲ್ಲಿ ಪಾಲು",
    caseHusbandDesc: "ವಿಧವೆಯಾಗಿ ಪತಿಯ ಆಸ್ತಿಯಲ್ಲಿ ಪಾಲು ಬೇಕು.",
    caseDeniedTitle: "ಸಹೋದರರು / ಕುಟುಂಬ ನನ್ನ ಪಾಲು ನಿರಾಕರಿಸುತ್ತಿದ್ದಾರೆ",
    caseDeniedDesc: "ಆಸ್ತಿ ಇದೆ ಆದರೆ ಸಂಬಂಧಿಕರು ಹಕ್ಕು ಕೊಡುತ್ತಿಲ್ಲ.",
    caseAgriTitle: "ಕೃಷಿ ಭೂಮಿ / ಪಟ್ಟಾ ವಿವಾದ",
    caseAgriDesc: "ಕೃಷಿ ಭೂಮಿ, ಪಟ್ಟಾ ಅಥವಾ ಕಂದಾಯ ದಾಖಲೆಗಳ ಬಗ್ಗೆ.",
    qWillTitle: "ಮರಣ ಹೊಂದಿದವರು ಉಯಿಲು ಬರೆದಿದ್ದರೆ?",
    qWillYes: "ಹೌದು, ಉಯಿಲು ಇದೆ", qWillNo: "ಉಯಿಲು ಇಲ್ಲ", qWillUnknown: "ನನಗೆ ಗೊತ್ತಿಲ್ಲ",
    qReligionTitle: "ಕುಟುಂಬದ ಧರ್ಮ ಯಾವುದು?",
    qHindu: "ಹಿಂದೂ / ಸಿಖ್ / ಜೈನ / ಬೌದ್ಧ", qMuslim: "ಮುಸ್ಲಿಂ", qChristian: "ಕ್ರೈಸ್ತ", qOther: "ಇತರೆ",
    qLandTitle: "ಕೃಷಿ ಭೂಮಿ ಒಳಗೊಂಡಿದೆಯೇ?",
    qLandYes: "ಹೌದು", qLandNo: "ಇಲ್ಲ, ಮನೆ / ಹಣ / ಚಿನ್ನ ಮಾತ್ರ",
    nextFatherDLSA: "DLSA-ಗೆ ಭೇಟಿ ನೀಡಿ ಕಾನೂನು ವಾರಸುದಾರ ಪ್ರಮಾಣಪತ್ರಕ್ಕೆ ಉಚಿತ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
    nextFatherMutation: "ತಹಶೀಲ್ ಕಚೇರಿಯಲ್ಲಿ ಮ್ಯುಟೇಶನ್‌ಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
    nextFatherFIR: "ಸಂಬಂಧಿಕರು ದಾಖಲೆ ಮರೆಮಾಡಿದರೆ ಪೊಲೀಸ್ ಠಾಣೆಯಲ್ಲಿ ಲಿಖಿತ ದೂರು ನೀಡಿ.",
    nextHusbandSuccession: "ಬ್ಯಾಂಕ್ ಖಾತೆ ಮತ್ತು ಚರ ಆಸ್ತಿಗೆ ಸಿವಿಲ್ ಕೋರ್ಟ್‌ನಿಂದ ಉತ್ತರಾಧಿಕಾರ ಪ್ರಮಾಣಪತ್ರ ಪಡೆಯಿರಿ.",
    nextHusbandShare: "ವಿಧವೆಯಾಗಿ ನೀವು Class I ವಾರಸುದಾರರು — ಮಕ್ಕಳಂತೆ ಸಮಾನ ಪಾಲು.",
    nextDeniedNotice: "DLSA ವಕೀಲರ ಮೂಲಕ ಉಚಿತ ಕಾನೂನು ನೋಟಿಸ್ ಕಳುಹಿಸಿ.",
    nextDeniedSection6: "2005 ರಿಂದ ಹೆಣ್ಣುಮಕ್ಕಳಿಗೆ ಸಮಾನ ಹಕ್ಕು (ಹಿಂದೂ ಉತ್ತರಾಧಿಕಾರ ಕಾಯ್ದೆ, ಸೆಕ್ಷನ್ 6).",
    nextAgriPatta: "ಗ್ರಾಮ ಪಟ್ವಾರಿ/ತಲಾಟಿಯಿಂದ ಇತ್ತೀಚಿನ ಪಟ್ಟಾ ಪಡೆಯಿರಿ.",
    nextAgriRevenue: "ತಹಶೀಲ್ದಾರ್‌ಗೆ ಮ್ಯುಟೇಶನ್ ಅರ್ಜಿ; ನಿರಾಕರಿಸಿದರೆ SDM-ಗೆ ಮೇಲ್ಮನವಿ.",
  },
  ml: {
    tagline: "നിങ്ങളുടെ ശബ്ദം. നിങ്ങളുടെ അവകാശങ്ങൾ. നിങ്ങളുടെ പിന്തുടർച്ചാവകാശം.",
    subtitle: "ഗ്രാമീണ സ്ത്രീകൾക്കായുള്ള ലളിതമായ ശബ്ദ സഹായി — സ്വന്തം ഭാഷയിൽ പിന്തുടർച്ചാവകാശം മനസ്സിലാക്കുക.",
    heroCtaPrimary: "സംസാരിക്കാൻ തുടങ്ങുക", heroCtaSecondary: "നിയമ സഹായം", heroCtaGuidance: "ലളിത നിയമ മാർഗനിർദേശം",
    chooseLanguage: "നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക",
    chatPlaceholder: "ടൈപ്പ് ചെയ്യുക അല്ലെങ്കിൽ മൈക്ക് അമർത്തുക…",
    send: "അയയ്ക്കുക", tapToSpeak: "സംസാരിക്കാൻ അമർത്തുക", listening: "കേൾക്കുന്നു…", speaking: "സംസാരിക്കുന്നു…",
    directoryTitle: "സമീപത്തെ നിയമ സഹായം", directorySub: "ഇന്ത്യയിലുടനീളം സൗജന്യ നിയമ സഹായം, NGO, ഹെൽപ്പ്‌ലൈൻ.",
    selectState: "നിങ്ങളുടെ സംസ്ഥാനം തിരഞ്ഞെടുക്കുക", callNow: "ഇപ്പോൾ വിളിക്കുക",
    lawyers: "നിയമ സഹായം", ngos: "എൻജിഒ", helplines: "ഹെൽപ്പ്‌ലൈൻ",
    all: "എല്ലാം", search: "തിരയുക…", noResults: "സമ്പർക്കങ്ങൾ കണ്ടെത്തിയില്ല.",
    guidanceTitle: "വോയ്‌സ് ചാറ്റ്‌ബോട്ട്", guidanceSub: "നിങ്ങളുടെ പിന്തുടർച്ചാവകാശം ചോദിക്കുക.",
    disclaimer: "ഇത് പൊതുവിവരം മാത്രം, വക്കീലിന് പകരമല്ല.", back: "തിരികെ",
    feature1Title: "നിങ്ങളുടെ ഭാഷയിൽ സംസാരിക്കുക", feature1Desc: "12 ഇന്ത്യൻ ഭാഷകളിൽ ശബ്ദത്തിൽ.",
    feature2Title: "ലളിത നിയമ ഉപദേശം", feature2Desc: "നിങ്ങളുടെ വിഹിതം, പെൺമക്കളുടെ അവകാശങ്ങൾ — ലളിതമായി.",
    feature3Title: "സമീപത്ത് യഥാർത്ഥ സഹായം", feature3Desc: "നിങ്ങളുടെ സംസ്ഥാനത്തെ നിയമ സഹായവും ഹെൽപ്പ്‌ലൈനും.",
    forRuralWomen: "ഇന്ത്യയിലെ ഗ്രാമീണ സ്ത്രീകൾക്കായി · 12 ഭാഷകൾ",
    talkingIn: "സംസാരിക്കുന്നത്", womenHelpline: "വനിതാ ഹെൽപ്പ്‌ലൈൻ · 24×7",
    ctaTitle: "നിങ്ങളുടെ അവകാശങ്ങൾ അറിയാൻ തയ്യാറാണോ?",
    ctaDesc: "സ്വന്തം ഭാഷയിൽ സംസാരിക്കുക. വായിക്കേണ്ട ആവശ്യമില്ല.",
    footerNote: "ഇന്ത്യൻ സ്ത്രീകൾക്കായി സ്നേഹത്തോടെ.",
    docsTitle: "ആവശ്യമായ രേഖകൾ", docsSub: "പിന്തുടർച്ചയും സ്വത്തുമായി ബന്ധപ്പെട്ട കേസുകളിൽ വേണ്ട രേഖകൾ.",
    docsIdentity: "ഐഡന്റിറ്റി തെളിവ്", docsIdentityDesc: "ആധാർ, വോട്ടർ ഐഡി, പാൻ, റേഷൻ കാർഡ് അല്ലെങ്കിൽ പാസ്‌പോർട്ട്.",
    docsProperty: "സ്വത്ത് രേഖകൾ", docsPropertyDesc: "വിൽപ്പന ആധാരം, ദാന ആധാരം, പട്ടാ, നികുതി രസീത്.",
    docsRelationship: "ബന്ധത്തിന്റെ തെളിവ്", docsRelationshipDesc: "ജനന സർട്ടിഫിക്കറ്റ്, വിവാഹ സർട്ടിഫിക്കറ്റ്, കുടുംബ വൃക്ഷം.",
    docsDeath: "മരണ സംബന്ധിയ രേഖകൾ", docsDeathDesc: "മരണ സർട്ടിഫിക്കറ്റും വിൽപ്പത്രവും (ഉണ്ടെങ്കിൽ).",
    docsLegal: "നിയമ സർട്ടിഫിക്കറ്റുകൾ", docsLegalDesc: "നിയമ അനന്തരാവകാശ സർട്ടിഫിക്കറ്റ് — തഹസിൽദാർ അല്ലെങ്കിൽ സിവിൽ കോടതിയിൽ നിന്ന്.",
    docsTip: "സഹായകരമായ നുറുങ്ങ്", docsTipText: "സമീപത്തെ ജില്ലാ നിയമ സേവന അതോറിറ്റി (DLSA) സന്ദർശിക്കുക — സൗജന്യ സഹായം.",
    wizardIntro: "1–2 ചെറിയ ചോദ്യങ്ങൾക്ക് ഉത്തരം നൽകുക — നിങ്ങൾക്ക് ആവശ്യമുള്ള രേഖകൾ മാത്രം കാണിക്കും.",
    wizardPickCase: "നിങ്ങളുടെ സാഹചര്യം എന്താണ്?",
    wizardStep: "ഘട്ടം", wizardOf: "ൽ", wizardNext: "അടുത്തത്", wizardPrev: "പിന്നോട്ട്",
    wizardRestart: "വീണ്ടും തുടങ്ങുക",
    wizardYourChecklist: "നിങ്ങളുടെ വ്യക്തിഗത പട്ടിക",
    wizardWhyThis: "ഈ രേഖകൾ എന്തിന്?",
    wizardNextSteps: "ഇനി എന്ത് ചെയ്യണം",
    wizardAskChat: "ന്യായസഖിയോട് ചോദിക്കുക",
    wizardFindHelp: "സമീപത്ത് നിയമ സഹായം കണ്ടെത്തുക",
    caseFatherTitle: "അച്ഛൻ മരിച്ചു — അദ്ദേഹത്തിന്റെ സ്വത്തിൽ വിഹിതം",
    caseFatherDesc: "അച്ഛന്റെ ഭൂമി, വീട് അല്ലെങ്കിൽ പണത്തിൽ നിങ്ങളുടെ വിഹിതം വേണം.",
    caseHusbandTitle: "ഭർത്താവ് മരിച്ചു — അദ്ദേഹത്തിന്റെ സ്വത്തിൽ വിഹിതം",
    caseHusbandDesc: "വിധവയായി ഭർത്താവിന്റെ സ്വത്തിൽ വിഹിതം വേണം.",
    caseDeniedTitle: "സഹോദരങ്ങൾ / കുടുംബം എന്റെ വിഹിതം നിഷേധിക്കുന്നു",
    caseDeniedDesc: "സ്വത്തുണ്ട് പക്ഷേ ബന്ധുക്കൾ അവകാശം നൽകുന്നില്ല.",
    caseAgriTitle: "കാർഷിക ഭൂമി / പട്ടാ തർക്കം",
    caseAgriDesc: "കൃഷിഭൂമി, പട്ടാ അല്ലെങ്കിൽ റവന്യൂ രേഖകളെക്കുറിച്ച്.",
    qWillTitle: "മരിച്ചയാൾ വിൽപ്പത്രം എഴുതിയിരുന്നോ?",
    qWillYes: "അതെ, വിൽപ്പത്രമുണ്ട്", qWillNo: "വിൽപ്പത്രമില്ല", qWillUnknown: "എനിക്കറിയില്ല",
    qReligionTitle: "കുടുംബത്തിന്റെ മതം ഏതാണ്?",
    qHindu: "ഹിന്ദു / സിഖ് / ജൈന / ബുദ്ധ", qMuslim: "മുസ്ലിം", qChristian: "ക്രിസ്ത്യൻ", qOther: "മറ്റുള്ളവ",
    qLandTitle: "കാർഷിക ഭൂമി ഉൾപ്പെട്ടിട്ടുണ്ടോ?",
    qLandYes: "അതെ", qLandNo: "ഇല്ല, വീട് / പണം / സ്വർണം മാത്രം",
    nextFatherDLSA: "DLSA സന്ദർശിച്ച് നിയമ അനന്തരാവകാശ സർട്ടിഫിക്കറ്റിന് സൗജന്യമായി അപേക്ഷിക്കുക.",
    nextFatherMutation: "തഹസിൽ ഓഫീസിൽ മ്യൂട്ടേഷനായി അപേക്ഷിക്കുക.",
    nextFatherFIR: "ബന്ധുക്കൾ രേഖകൾ മറച്ചാൽ പോലീസ് സ്റ്റേഷനിൽ രേഖാമൂലം പരാതി നൽകുക.",
    nextHusbandSuccession: "ബാങ്ക് അക്കൗണ്ടുകൾക്കും ജംഗമ സ്വത്തിനും സിവിൽ കോടതിയിൽ നിന്ന് അനന്തരാവകാശ സർട്ടിഫിക്കറ്റ് നേടുക.",
    nextHusbandShare: "വിധവയായി നിങ്ങൾ Class I അവകാശിയാണ് — കുട്ടികളോടൊപ്പം തുല്യ വിഹിതം.",
    nextDeniedNotice: "DLSA വക്കീൽ വഴി സൗജന്യ നിയമ നോട്ടീസ് അയയ്ക്കുക.",
    nextDeniedSection6: "2005 മുതൽ പെൺമക്കൾക്ക് തുല്യ അവകാശം (ഹിന്ദു അനന്തരാവകാശ നിയമം, വകുപ്പ് 6).",
    nextAgriPatta: "ഗ്രാമ വില്ലേജ് ഓഫീസിൽ നിന്ന് ഏറ്റവും പുതിയ പട്ടാ വാങ്ങുക.",
    nextAgriRevenue: "തഹസിൽദാർക്ക് മ്യൂട്ടേഷൻ അപേക്ഷ; നിരസിച്ചാൽ SDM-ന് അപ്പീൽ.",
  },
  pa: {
    tagline: "ਤੁਹਾਡੀ ਆਵਾਜ਼। ਤੁਹਾਡੇ ਹੱਕ। ਤੁਹਾਡੀ ਵਿਰਾਸਤ।",
    subtitle: "ਪੇਂਡੂ ਔਰਤਾਂ ਲਈ ਸੌਖਾ ਆਵਾਜ਼-ਅਧਾਰਤ ਸਾਥੀ — ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਵਿਰਾਸਤ ਦੇ ਹੱਕ ਸਮਝੋ।",
    heroCtaPrimary: "ਗੱਲ ਸ਼ੁਰੂ ਕਰੋ", heroCtaSecondary: "ਕਾਨੂੰਨੀ ਮਦਦ ਲੱਭੋ", heroCtaGuidance: "ਸੌਖੀ ਕਾਨੂੰਨੀ ਸੇਧ",
    chooseLanguage: "ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ",
    chatPlaceholder: "ਲਿਖੋ ਜਾਂ ਮਾਈਕ ਦਬਾਓ…",
    send: "ਭੇਜੋ", tapToSpeak: "ਬੋਲਣ ਲਈ ਦਬਾਓ", listening: "ਸੁਣ ਰਹੀ ਹਾਂ…", speaking: "ਬੋਲ ਰਹੀ ਹਾਂ…",
    directoryTitle: "ਨੇੜਲੀ ਕਾਨੂੰਨੀ ਮਦਦ", directorySub: "ਮੁਫ਼ਤ ਕਾਨੂੰਨੀ ਸਹਾਇਤਾ, NGO ਅਤੇ ਮਹਿਲਾ ਹੈਲਪਲਾਈਨ।",
    selectState: "ਆਪਣਾ ਰਾਜ ਚੁਣੋ", callNow: "ਹੁਣੇ ਕਾਲ ਕਰੋ",
    lawyers: "ਕਾਨੂੰਨੀ ਸਹਾਇਤਾ", ngos: "ਐਨਜੀਓ", helplines: "ਹੈਲਪਲਾਈਨ",
    all: "ਸਾਰੇ", search: "ਖੋਜੋ…", noResults: "ਕੋਈ ਸੰਪਰਕ ਨਹੀਂ ਮਿਲਿਆ।",
    guidanceTitle: "ਆਵਾਜ਼ ਚੈਟਬੋਟ", guidanceSub: "ਵਿਰਾਸਤ ਦੇ ਹੱਕਾਂ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ।",
    disclaimer: "ਇਹ ਆਮ ਜਾਣਕਾਰੀ ਹੈ, ਵਕੀਲ ਦਾ ਬਦਲ ਨਹੀਂ।", back: "ਵਾਪਸ",
    feature1Title: "ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਗੱਲ", feature1Desc: "12 ਭਾਰਤੀ ਭਾਸ਼ਾਵਾਂ ਵਿੱਚ ਆਵਾਜ਼ ਨਾਲ।",
    feature2Title: "ਸੌਖੀ ਕਾਨੂੰਨੀ ਸਲਾਹ", feature2Desc: "ਤੁਹਾਡਾ ਹਿੱਸਾ, ਧੀਆਂ ਦੇ ਹੱਕ ਅਤੇ ਕਾਨੂੰਨ — ਸੌਖੀ ਭਾਸ਼ਾ ਵਿੱਚ।",
    feature3Title: "ਨੇੜੇ ਅਸਲੀ ਮਦਦ", feature3Desc: "ਤੁਹਾਡੇ ਰਾਜ ਦੀ ਕਾਨੂੰਨੀ ਸਹਾਇਤਾ ਅਤੇ ਮਹਿਲਾ ਹੈਲਪਲਾਈਨ।",
    forRuralWomen: "ਭਾਰਤ ਦੀਆਂ ਪੇਂਡੂ ਔਰਤਾਂ ਲਈ · 12 ਭਾਸ਼ਾਵਾਂ",
    talkingIn: "ਗੱਲਬਾਤ", womenHelpline: "ਮਹਿਲਾ ਹੈਲਪਲਾਈਨ · 24×7",
    ctaTitle: "ਆਪਣੇ ਹੱਕ ਜਾਣਨ ਲਈ ਤਿਆਰ?",
    ctaDesc: "ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਬੋਲੋ। ਪੜ੍ਹਨ ਦੀ ਲੋੜ ਨਹੀਂ।",
    footerNote: "ਭਾਰਤ ਦੀਆਂ ਔਰਤਾਂ ਲਈ ਪਿਆਰ ਨਾਲ ਬਣਾਇਆ।",
    docsTitle: "ਜ਼ਰੂਰੀ ਦਸਤਾਵੇਜ਼", docsSub: "ਵਿਰਾਸਤ ਅਤੇ ਜਾਇਦਾਦ ਮਾਮਲਿਆਂ ਵਿੱਚ ਕੰਮ ਆਉਣ ਵਾਲੇ ਕਾਗਜ਼।",
    docsIdentity: "ਪਛਾਣ ਸਬੂਤ", docsIdentityDesc: "ਆਧਾਰ, ਵੋਟਰ ਆਈਡੀ, ਪੈਨ, ਰਾਸ਼ਨ ਕਾਰਡ ਜਾਂ ਪਾਸਪੋਰਟ।",
    docsProperty: "ਜਾਇਦਾਦ ਦੇ ਦਸਤਾਵੇਜ਼", docsPropertyDesc: "ਵਿਕਰੀ ਨਾਮਾ, ਦਾਨ ਨਾਮਾ, ਪੱਟਾ, ਜਾਇਦਾਦ ਟੈਕਸ ਰਸੀਦ।",
    docsRelationship: "ਰਿਸ਼ਤੇ ਦਾ ਸਬੂਤ", docsRelationshipDesc: "ਜਨਮ ਸਰਟੀਫਿਕੇਟ, ਵਿਆਹ ਸਰਟੀਫਿਕੇਟ, ਵੰਸ਼ਾਵਲੀ।",
    docsDeath: "ਮੌਤ ਨਾਲ ਜੁੜੇ ਕਾਗਜ਼", docsDeathDesc: "ਮੌਤ ਸਰਟੀਫਿਕੇਟ ਅਤੇ ਵਸੀਅਤ (ਜੇ ਹੋਵੇ)।",
    docsLegal: "ਕਾਨੂੰਨੀ ਸਰਟੀਫਿਕੇਟ", docsLegalDesc: "ਕਾਨੂੰਨੀ ਵਾਰਸ ਸਰਟੀਫਿਕੇਟ — ਤਹਿਸੀਲਦਾਰ ਜਾਂ ਸਿਵਲ ਕੋਰਟ ਤੋਂ।",
    docsTip: "ਮਦਦਗਾਰ ਸੁਝਾਅ", docsTipText: "ਨੇੜਲੇ ਜ਼ਿਲ੍ਹਾ ਕਾਨੂੰਨੀ ਸੇਵਾਵਾਂ ਅਥਾਰਟੀ (DLSA) ਜਾਓ — ਮੁਫ਼ਤ ਮਦਦ।",
    wizardIntro: "1–2 ਛੋਟੇ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਦਿਓ — ਅਸੀਂ ਸਿਰਫ਼ ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼ ਦਿਖਾਵਾਂਗੇ।",
    wizardPickCase: "ਤੁਹਾਡੀ ਸਥਿਤੀ ਕੀ ਹੈ?",
    wizardStep: "ਕਦਮ", wizardOf: "ਵਿੱਚੋਂ", wizardNext: "ਅੱਗੇ", wizardPrev: "ਪਿੱਛੇ",
    wizardRestart: "ਮੁੜ ਸ਼ੁਰੂ ਕਰੋ",
    wizardYourChecklist: "ਤੁਹਾਡੀ ਨਿੱਜੀ ਸੂਚੀ",
    wizardWhyThis: "ਇਹ ਦਸਤਾਵੇਜ਼ ਕਿਉਂ?",
    wizardNextSteps: "ਅੱਗੇ ਕੀ ਕਰਨਾ ਹੈ",
    wizardAskChat: "ਨਿਆਂਸਖੀ ਨੂੰ ਪੁੱਛੋ",
    wizardFindHelp: "ਨੇੜੇ ਕਾਨੂੰਨੀ ਮਦਦ ਲੱਭੋ",
    caseFatherTitle: "ਪਿਤਾ ਦੀ ਮੌਤ — ਉਨ੍ਹਾਂ ਦੀ ਜਾਇਦਾਦ ਵਿੱਚ ਹਿੱਸਾ",
    caseFatherDesc: "ਪਿਤਾ ਦੀ ਜ਼ਮੀਨ, ਘਰ ਜਾਂ ਪੈਸੇ ਵਿੱਚ ਤੁਹਾਡਾ ਹਿੱਸਾ ਚਾਹੀਦਾ ਹੈ।",
    caseHusbandTitle: "ਪਤੀ ਦੀ ਮੌਤ — ਉਨ੍ਹਾਂ ਦੀ ਜਾਇਦਾਦ ਵਿੱਚ ਹਿੱਸਾ",
    caseHusbandDesc: "ਵਿਧਵਾ ਵਜੋਂ ਪਤੀ ਦੀ ਜਾਇਦਾਦ ਵਿੱਚ ਹਿੱਸਾ ਚਾਹੀਦਾ।",
    caseDeniedTitle: "ਭਰਾ / ਪਰਿਵਾਰ ਮੇਰਾ ਹਿੱਸਾ ਨਹੀਂ ਦੇ ਰਹੇ",
    caseDeniedDesc: "ਜਾਇਦਾਦ ਹੈ ਪਰ ਰਿਸ਼ਤੇਦਾਰ ਹੱਕ ਨਹੀਂ ਦੇ ਰਹੇ।",
    caseAgriTitle: "ਖੇਤੀ ਜ਼ਮੀਨ / ਪੱਟਾ ਵਿਵਾਦ",
    caseAgriDesc: "ਖੇਤੀ, ਪੱਟਾ ਜਾਂ ਮਾਲੀਆ ਰਿਕਾਰਡ ਬਾਰੇ।",
    qWillTitle: "ਕੀ ਮਰਨ ਵਾਲੇ ਨੇ ਵਸੀਅਤ ਲਿਖੀ ਸੀ?",
    qWillYes: "ਹਾਂ, ਵਸੀਅਤ ਹੈ", qWillNo: "ਵਸੀਅਤ ਨਹੀਂ", qWillUnknown: "ਮੈਨੂੰ ਨਹੀਂ ਪਤਾ",
    qReligionTitle: "ਪਰਿਵਾਰ ਦਾ ਧਰਮ ਕੀ ਹੈ?",
    qHindu: "ਹਿੰਦੂ / ਸਿੱਖ / ਜੈਨ / ਬੋਧੀ", qMuslim: "ਮੁਸਲਿਮ", qChristian: "ਈਸਾਈ", qOther: "ਹੋਰ",
    qLandTitle: "ਕੀ ਖੇਤੀ ਜ਼ਮੀਨ ਸ਼ਾਮਲ ਹੈ?",
    qLandYes: "ਹਾਂ", qLandNo: "ਨਹੀਂ, ਸਿਰਫ਼ ਘਰ / ਪੈਸੇ / ਸੋਨਾ",
    nextFatherDLSA: "DLSA ਜਾਓ — ਕਾਨੂੰਨੀ ਵਾਰਸ ਸਰਟੀਫਿਕੇਟ ਲਈ ਮੁਫ਼ਤ ਅਰਜ਼ੀ ਦਿਓ।",
    nextFatherMutation: "ਤਹਿਸੀਲ ਦਫ਼ਤਰ ਵਿੱਚ ਇੰਤਕਾਲ ਲਈ ਅਰਜ਼ੀ ਦਿਓ।",
    nextFatherFIR: "ਰਿਸ਼ਤੇਦਾਰ ਕਾਗਜ਼ ਛੁਪਾਉਣ ਤਾਂ ਥਾਣੇ ਵਿੱਚ ਲਿਖਤੀ ਸ਼ਿਕਾਇਤ ਦਿਓ।",
    nextHusbandSuccession: "ਬੈਂਕ ਖਾਤੇ ਅਤੇ ਚੱਲ ਜਾਇਦਾਦ ਲਈ ਸਿਵਲ ਕੋਰਟ ਤੋਂ ਉੱਤਰਾਧਿਕਾਰ ਸਰਟੀਫਿਕੇਟ ਲਓ।",
    nextHusbandShare: "ਵਿਧਵਾ ਵਜੋਂ ਤੁਸੀਂ Class I ਵਾਰਸ ਹੋ — ਬੱਚਿਆਂ ਬਰਾਬਰ ਹਿੱਸਾ।",
    nextDeniedNotice: "DLSA ਵਕੀਲ ਰਾਹੀਂ ਮੁਫ਼ਤ ਕਾਨੂੰਨੀ ਨੋਟਿਸ ਭੇਜੋ।",
    nextDeniedSection6: "2005 ਤੋਂ ਧੀਆਂ ਨੂੰ ਬਰਾਬਰ ਹੱਕ (ਹਿੰਦੂ ਉੱਤਰਾਧਿਕਾਰ ਐਕਟ, ਧਾਰਾ 6)।",
    nextAgriPatta: "ਪਿੰਡ ਦੇ ਪਟਵਾਰੀ ਤੋਂ ਤਾਜ਼ਾ ਜ਼ਮੀਨ ਦਾ ਰਿਕਾਰਡ ਲਓ।",
    nextAgriRevenue: "ਤਹਿਸੀਲਦਾਰ ਕੋਲ ਇੰਤਕਾਲ ਅਰਜ਼ੀ; ਨਾਮਨਜ਼ੂਰ ਹੋਣ 'ਤੇ SDM ਕੋਲ ਅਪੀਲ।",
  },
  or: {
    tagline: "ଆପଣଙ୍କ ସ୍ୱର। ଆପଣଙ୍କ ଅଧିକାର। ଆପଣଙ୍କ ଉତ୍ତରାଧିକାର।",
    subtitle: "ଗ୍ରାମୀଣ ମହିଳାମାନଙ୍କ ପାଇଁ ସରଳ ସ୍ୱର-ଆଧାରିତ ସାଥୀ।",
    heroCtaPrimary: "କଥା ଆରମ୍ଭ କରନ୍ତୁ", heroCtaSecondary: "ଆଇନଗତ ସହାୟତା", heroCtaGuidance: "ସରଳ ଆଇନଗତ ମାର୍ଗଦର୍ଶନ",
    chooseLanguage: "ଆପଣଙ୍କ ଭାଷା ବାଛନ୍ତୁ",
    chatPlaceholder: "ଲେଖନ୍ତୁ ବା ମାଇକ ଦବାନ୍ତୁ…",
    send: "ପଠାନ୍ତୁ", tapToSpeak: "କହିବାକୁ ଦବାନ୍ତୁ", listening: "ଶୁଣୁଛି…", speaking: "କହୁଛି…",
    directoryTitle: "ନିକଟସ୍ଥ ଆଇନଗତ ସହାୟତା", directorySub: "ମାଗଣା ଆଇନଗତ ସହାୟତା, NGO, ହେଲ୍ପଲାଇନ୍।",
    selectState: "ଆପଣଙ୍କ ରାଜ୍ୟ ବାଛନ୍ତୁ", callNow: "ବର୍ତ୍ତମାନ କଲ କରନ୍ତୁ",
    lawyers: "ଆଇନଗତ ସହାୟତା", ngos: "ଏନଜିଓ", helplines: "ହେଲ୍ପଲାଇନ",
    all: "ସବୁ", search: "ଖୋଜନ୍ତୁ…", noResults: "କୌଣସି ସମ୍ପର୍କ ମିଳିଲା ନାହିଁ।",
    guidanceTitle: "ସ୍ୱର ଚାଟବଟ", guidanceSub: "ଉତ୍ତରାଧିକାର ବିଷୟରେ ପଚାରନ୍ତୁ।",
    disclaimer: "ଏହା ସାଧାରଣ ତଥ୍ୟ, ଆଇନଜୀବୀଙ୍କ ବିକଳ୍ପ ନୁହେଁ।", back: "ପଛକୁ",
    feature1Title: "ନିଜ ଭାଷାରେ କଥା", feature1Desc: "12ଟି ଭାରତୀୟ ଭାଷାରେ।",
    feature2Title: "ସରଳ ଆଇନଗତ ସଲାହ", feature2Desc: "ଆପଣଙ୍କ ଅଂଶ, ଝିଅମାନଙ୍କ ଅଧିକାର।",
    feature3Title: "ନିକଟରେ ଅସଲ ସହାୟତା", feature3Desc: "ରାଜ୍ୟର ଆଇନଗତ ସହାୟତା ଓ ହେଲ୍ପଲାଇନ୍।",
    forRuralWomen: "ଭାରତର ଗ୍ରାମୀଣ ମହିଳାମାନଙ୍କ ପାଇଁ · 12 ଭାଷା",
    talkingIn: "କଥା ହେଉଛି", womenHelpline: "ମହିଳା ହେଲ୍ପଲାଇନ · 24×7",
    ctaTitle: "ଆପଣଙ୍କ ଅଧିକାର ଜାଣିବା ପାଇଁ ପ୍ରସ୍ତୁତ?",
    ctaDesc: "ନିଜ ଭାଷାରେ କୁହନ୍ତୁ।",
    footerNote: "ଭାରତର ମହିଳାମାନଙ୍କ ପାଇଁ ସ୍ନେହର ସହ।",
    docsTitle: "ଆବଶ୍ୟକ କାଗଜପତ୍ର", docsSub: "ଉତ୍ତରାଧିକାର ମାମଲାରେ ଲୋଡ଼ା କାଗଜର ତାଲିକା।",
    docsIdentity: "ପରିଚୟ ପ୍ରମାଣ", docsIdentityDesc: "ଆଧାର, ଭୋଟର ID, ପ୍ୟାନ, ରେସନ କାର୍ଡ।",
    docsProperty: "ସମ୍ପତ୍ତି କାଗଜ", docsPropertyDesc: "ବିକ୍ରୟ ଦଲିଲ, ଦାନ ଦଲିଲ, ପଟ୍ଟା, ଟ୍ୟାକ୍ସ ରସିଦ।",
    docsRelationship: "ସମ୍ପର୍କ ପ୍ରମାଣ", docsRelationshipDesc: "ଜନ୍ମ ସର୍ଟିଫିକେଟ, ବିବାହ ସର୍ଟିଫିକେଟ।",
    docsDeath: "ମୃତ୍ୟୁ ସମ୍ବନ୍ଧୀୟ", docsDeathDesc: "ମୃତ୍ୟୁ ସର୍ଟିଫିକେଟ ଓ ଉଇଲ।",
    docsLegal: "ଆଇନଗତ ସର୍ଟିଫିକେଟ", docsLegalDesc: "ଉତ୍ତରାଧିକାର ସର୍ଟିଫିକେଟ — ତହସିଲଦାରଙ୍କଠାରୁ।",
    docsTip: "ସହାୟକ ସୂଚନା", docsTipText: "ନିକଟସ୍ଥ DLSAକୁ ଯାଆନ୍ତୁ — ମାଗଣା ସହାୟତା।",
    wizardIntro: "1–2ଟି ଛୋଟ ପ୍ରଶ୍ନର ଉତ୍ତର ଦିଅନ୍ତୁ — ଆମେ କେବଳ ଆବଶ୍ୟକ କାଗଜ ଦେଖାଇବୁ।",
    wizardPickCase: "ଆପଣଙ୍କ ପରିସ୍ଥିତି କଣ?",
    wizardStep: "ପଦକ୍ଷେପ", wizardOf: "ର", wizardNext: "ପରବର୍ତ୍ତୀ", wizardPrev: "ପଛକୁ",
    wizardRestart: "ପୁଣି ଆରମ୍ଭ କରନ୍ତୁ",
    wizardYourChecklist: "ଆପଣଙ୍କ ବ୍ୟକ୍ତିଗତ ତାଲିକା",
    wizardWhyThis: "ଏହି କାଗଜ କାହିଁକି?",
    wizardNextSteps: "ଏବେ କଣ କରିବେ",
    wizardAskChat: "ନ୍ୟାୟସଖୀଙ୍କୁ ପଚାରନ୍ତୁ",
    wizardFindHelp: "ନିକଟରେ ଆଇନଗତ ସହାୟତା ଖୋଜନ୍ତୁ",
    caseFatherTitle: "ବାପାଙ୍କ ମୃତ୍ୟୁ — ତାଙ୍କ ସମ୍ପତ୍ତିରେ ଅଂଶ",
    caseFatherDesc: "ବାପାଙ୍କ ଜମି, ଘର କିମ୍ବା ପଇସାରେ ଅଂଶ ଦରକାର।",
    caseHusbandTitle: "ସ୍ୱାମୀଙ୍କ ମୃତ୍ୟୁ — ତାଙ୍କ ସମ୍ପତ୍ତିରେ ଅଂଶ",
    caseHusbandDesc: "ବିଧବା ଭାବରେ ସ୍ୱାମୀଙ୍କ ସମ୍ପତ୍ତିରେ ଅଂଶ ଦରକାର।",
    caseDeniedTitle: "ଭାଇ / ପରିବାର ମୋ ଅଂଶ ଦେଉ ନାହାଁନ୍ତି",
    caseDeniedDesc: "ସମ୍ପତ୍ତି ଅଛି କିନ୍ତୁ ଆତ୍ମୀୟ ଅଧିକାର ଦେଉ ନାହାଁନ୍ତି।",
    caseAgriTitle: "କୃଷି ଜମି / ପଟ୍ଟା ବିବାଦ",
    caseAgriDesc: "କୃଷି ଜମି, ପଟ୍ଟା କିମ୍ବା ରାଜସ୍ୱ ରେକର୍ଡ ବିଷୟରେ।",
    qWillTitle: "ମୃତ ବ୍ୟକ୍ତି ଉଇଲ ଲେଖିଥିଲେ କି?",
    qWillYes: "ହଁ, ଉଇଲ ଅଛି", qWillNo: "ଉଇଲ ନାହିଁ", qWillUnknown: "ମୁଁ ଜାଣେ ନାହିଁ",
    qReligionTitle: "ପରିବାରର ଧର୍ମ କଣ?",
    qHindu: "ହିନ୍ଦୁ / ଶିଖ / ଜୈନ / ବୌଦ୍ଧ", qMuslim: "ମୁସଲିମ", qChristian: "ଖ୍ରୀଷ୍ଟିଆନ", qOther: "ଅନ୍ୟ",
    qLandTitle: "କୃଷି ଜମି ଜଡ଼ିତ କି?",
    qLandYes: "ହଁ", qLandNo: "ନା, କେବଳ ଘର / ପଇସା / ସୁନା",
    nextFatherDLSA: "DLSAକୁ ଯାଇ ଆଇନଗତ ଉତ୍ତରାଧିକାର ସର୍ଟିଫିକେଟ ପାଇଁ ମାଗଣା ଆବେଦନ କରନ୍ତୁ।",
    nextFatherMutation: "ତହସିଲ କାର୍ଯ୍ୟାଳୟରେ ମ୍ୟୁଟେସନ ପାଇଁ ଆବେଦନ କରନ୍ତୁ।",
    nextFatherFIR: "ଆତ୍ମୀୟ କାଗଜ ଲୁଚାଇଲେ ଥାନାରେ ଲିଖିତ ଅଭିଯୋଗ ଦିଅନ୍ତୁ।",
    nextHusbandSuccession: "ବ୍ୟାଙ୍କ ଖାତା ଓ ଚଳ ସମ୍ପତ୍ତି ପାଇଁ ସିଭିଲ କୋର୍ଟରୁ ଉତ୍ତରାଧିକାର ସର୍ଟିଫିକେଟ ନିଅନ୍ତୁ।",
    nextHusbandShare: "ବିଧବା ଭାବରେ ଆପଣ Class I ଉତ୍ତରାଧିକାରୀ — ପିଲାଙ୍କ ସହ ସମାନ ଅଂଶ।",
    nextDeniedNotice: "DLSA ଓକିଲଙ୍କ ମାଧ୍ୟମରେ ମାଗଣା ଆଇନଗତ ନୋଟିସ ପଠାନ୍ତୁ।",
    nextDeniedSection6: "2005ରୁ ଝିଅଙ୍କୁ ସମାନ ଅଧିକାର (ହିନ୍ଦୁ ଉତ୍ତରାଧିକାର ଆଇନ, ଧାରା 6)।",
    nextAgriPatta: "ଗ୍ରାମର ତଲାଟୀଙ୍କଠାରୁ ସର୍ବଶେଷ ପଟ୍ଟା ନିଅନ୍ତୁ।",
    nextAgriRevenue: "ତହସିଲଦାରଙ୍କ ନିକଟରେ ମ୍ୟୁଟେସନ ଆବେଦନ; ମନା ହେଲେ SDMଙ୍କ ନିକଟରେ ଅପିଲ।",
  },
  as: {
    tagline: "আপোনাৰ কণ্ঠ। আপোনাৰ অধিকাৰ। আপোনাৰ উত্তৰাধিকাৰ।",
    subtitle: "গ্ৰামীণ মহিলাসকলৰ বাবে সৰল কণ্ঠ-ভিত্তিক সহায়ক।",
    heroCtaPrimary: "কথা আৰম্ভ কৰক", heroCtaSecondary: "আইনী সহায়", heroCtaGuidance: "সৰল আইনী নিৰ্দেশনা",
    chooseLanguage: "আপোনাৰ ভাষা বাছনি কৰক",
    chatPlaceholder: "লিখক বা মাইক টিপক…",
    send: "পঠাওক", tapToSpeak: "কোৱাৰ বাবে টিপক", listening: "শুনি আছোঁ…", speaking: "কৈ আছোঁ…",
    directoryTitle: "ওচৰৰ আইনী সহায়", directorySub: "বিনামূলীয়া আইনী সহায়, NGO আৰু হেল্পলাইন।",
    selectState: "আপোনাৰ ৰাজ্য বাছনি কৰক", callNow: "এতিয়াই কল কৰক",
    lawyers: "আইনী সহায়", ngos: "এনজিঅ'", helplines: "হেল্পলাইন",
    all: "সকলো", search: "সন্ধান…", noResults: "কোনো যোগাযোগ পোৱা নগ'ল।",
    guidanceTitle: "ভইচ চেটবট", guidanceSub: "উত্তৰাধিকাৰ সম্পৰ্কে যিকোনো প্ৰশ্ন কৰক।",
    disclaimer: "এইটো সাধাৰণ তথ্য, উকিলৰ বিকল্প নহয়।", back: "পিছলৈ",
    feature1Title: "নিজৰ ভাষাত কথা", feature1Desc: "12 টা ভাৰতীয় ভাষাত।",
    feature2Title: "সৰল আইনী পৰামৰ্শ", feature2Desc: "আপোনাৰ অংশ, ছোৱালীৰ অধিকাৰ।",
    feature3Title: "ওচৰতে প্ৰকৃত সহায়", feature3Desc: "ৰাজ্যৰ আইনী সহায় আৰু হেল্পলাইন।",
    forRuralWomen: "ভাৰতৰ গ্ৰামীণ মহিলাসকলৰ বাবে · 12 ভাষা",
    talkingIn: "কথা চলিছে", womenHelpline: "মহিলা হেল্পলাইন · 24×7",
    ctaTitle: "আপোনাৰ অধিকাৰ জানিবলৈ সাজু?",
    ctaDesc: "নিজৰ ভাষাত কওক।",
    footerNote: "ভাৰতৰ মহিলাসকলৰ বাবে স্নেহেৰে নিৰ্মিত।",
    docsTitle: "প্ৰয়োজনীয় কাগজপত্ৰ", docsSub: "উত্তৰাধিকাৰ আৰু সম্পত্তি গোচৰত প্ৰয়োজনীয় কাগজৰ তালিকা।",
    docsIdentity: "পৰিচয়ৰ প্ৰমাণ", docsIdentityDesc: "আধাৰ, ভোটাৰ ID, পেন, ৰেচন কাৰ্ড।",
    docsProperty: "সম্পত্তিৰ কাগজ", docsPropertyDesc: "বিক্ৰী দলিল, দান দলিল, পট্টা, কৰ ৰচিদ।",
    docsRelationship: "সম্পৰ্কৰ প্ৰমাণ", docsRelationshipDesc: "জন্ম প্ৰমাণপত্ৰ, বিবাহ প্ৰমাণপত্ৰ।",
    docsDeath: "মৃত্যু সম্পৰ্কীয় কাগজ", docsDeathDesc: "মৃত্যু প্ৰমাণপত্ৰ আৰু উইল।",
    docsLegal: "আইনী প্ৰমাণপত্ৰ", docsLegalDesc: "উত্তৰাধিকাৰ প্ৰমাণপত্ৰ — তহছিলদাৰৰ পৰা।",
    docsTip: "সহায়ক পৰামৰ্শ", docsTipText: "ওচৰৰ DLSAলৈ যাওক — বিনামূলীয়া সহায়।",
    wizardIntro: "1–2টা সৰু প্ৰশ্নৰ উত্তৰ দিয়ক — আমি কেৱল প্ৰয়োজনীয় কাগজ দেখুৱাম।",
    wizardPickCase: "আপোনাৰ পৰিস্থিতি কি?",
    wizardStep: "পদক্ষেপ", wizardOf: "ৰ", wizardNext: "পৰৱৰ্তী", wizardPrev: "পিছলৈ",
    wizardRestart: "পুনৰ আৰম্ভ কৰক",
    wizardYourChecklist: "আপোনাৰ ব্যক্তিগত তালিকা",
    wizardWhyThis: "এই কাগজ কিয়?",
    wizardNextSteps: "এতিয়া কি কৰিব",
    wizardAskChat: "ন্যায়সখীক সোধক",
    wizardFindHelp: "ওচৰত আইনী সহায় বিচাৰক",
    caseFatherTitle: "দেউতাৰ মৃত্যু — তেওঁৰ সম্পত্তিত অংশ",
    caseFatherDesc: "দেউতাৰ মাটি, ঘৰ বা ধনত আপোনাৰ অংশ লাগে।",
    caseHusbandTitle: "স্বামীৰ মৃত্যু — তেওঁৰ সম্পত্তিত অংশ",
    caseHusbandDesc: "বিধৱা হিচাপে স্বামীৰ সম্পত্তিত অংশ লাগে।",
    caseDeniedTitle: "ভাইসকল / পৰিয়ালে মোৰ অংশ দিয়া নাই",
    caseDeniedDesc: "সম্পত্তি আছে কিন্তু আত্মীয়সকলে অধিকাৰ দিয়া নাই।",
    caseAgriTitle: "কৃষি ভূমি / পট্টা বিবাদ",
    caseAgriDesc: "কৃষি, পট্টা বা ৰাজহ ৰেকৰ্ডৰ বিষয়ে।",
    qWillTitle: "মৃত ব্যক্তিয়ে উইল লিখিছিল নেকি?",
    qWillYes: "হয়, উইল আছে", qWillNo: "উইল নাই", qWillUnknown: "মই নাজানো",
    qReligionTitle: "পৰিয়ালৰ ধৰ্ম কি?",
    qHindu: "হিন্দু / শিখ / জৈন / বৌদ্ধ", qMuslim: "মুছলিম", qChristian: "খ্ৰীষ্টান", qOther: "আন",
    qLandTitle: "কৃষি ভূমি জড়িত নেকি?",
    qLandYes: "হয়", qLandNo: "নহয়, কেৱল ঘৰ / ধন / সোণ",
    nextFatherDLSA: "DLSAলৈ গৈ আইনী উত্তৰাধিকাৰ প্ৰমাণপত্ৰৰ বাবে বিনামূলীয়া আবেদন কৰক।",
    nextFatherMutation: "তহছিল কাৰ্যালয়ত মিউটেচনৰ বাবে আবেদন কৰক।",
    nextFatherFIR: "আত্মীয়ই কাগজ লুকুৱালে থানাত লিখিত অভিযোগ দিয়ক।",
    nextHusbandSuccession: "বেংক একাউণ্ট আৰু চল সম্পত্তিৰ বাবে চিভিল কোৰ্টৰ পৰা উত্তৰাধিকাৰ প্ৰমাণপত্ৰ লওক।",
    nextHusbandShare: "বিধৱা হিচাপে আপুনি Class I উত্তৰাধিকাৰী — সন্তানৰ সৈতে সমান অংশ।",
    nextDeniedNotice: "DLSA উকিলৰ যোগেদি বিনামূলীয়া আইনী জাননী পঠিয়াওক।",
    nextDeniedSection6: "2005ৰ পৰা ছোৱালীক সমান অধিকাৰ (হিন্দু উত্তৰাধিকাৰ আইন, ধাৰা 6)।",
    nextAgriPatta: "গাঁৱৰ পট্টাদাৰৰ পৰা শেহতীয়া পট্টা লওক।",
    nextAgriRevenue: "তহছিলদাৰৰ ওচৰত মিউটেচন আবেদন; নাকচ হ'লে SDMৰ ওচৰত আপীল।",
  },
};

export function t(lang: LangCode, key: StringKey): string {
  return UI[lang]?.[key] ?? UI.en[key] ?? key;
}
